#!/bin/bash

# iid dataset, with k_r = 0.7, 1.0
python federated_main.py --dataset=emnist-balanced --epochs=100 --local_ep=10 --lr=0.01 --frac=0.7 --num_samples_per_user=2400 --seed=42 --iid --agg_type=fedavg --fedavg_type=unweighted
python federated_main.py --dataset=emnist-balanced --epochs=100 --local_ep=10 --lr=0.01 --frac=0.8 --num_samples_per_user=2400 --seed=42 --iid --agg_type=fedavg --fedavg_type=unweighted
python federated_main.py --dataset=emnist-balanced --epochs=100 --local_ep=10 --lr=0.01 --frac=0.9 --num_samples_per_user=2400 --seed=42 --iid --agg_type=fedavg --fedavg_type=unweighted
python federated_main.py --dataset=emnist-balanced --epochs=100 --local_ep=10 --lr=0.01 --frac=1 --num_samples_per_user=2400 --seed=42 --iid --agg_type=fedavg --fedavg_type=unweighted

# non-iid dataset, with k_r = 0.7, unique_c = 1, num_non_iid_users = 1
python federated_main.py --dataset=emnist-balanced --epochs=100 --local_ep=10 --lr=0.01 --frac=0.7 --unequal --num_samples_per_user=2400 --seed=42 --num_unique_classes_non_iid=1 --num_non_iid_users=1 --agg_type=fedla && \
python federated_main.py --dataset=emnist-balanced --epochs=100 --local_ep=10 --lr=0.01 --frac=0.7 --unequal --num_samples_per_user=2400 --seed=42 --num_unique_classes_non_iid=1 --num_non_iid_users=1 --agg_type=fedavg --fedavg_type=unweighted && \
python federated_main.py --dataset=emnist-balanced --epochs=100 --local_ep=10 --lr=0.01 --frac=0.7 --unequal --num_samples_per_user=2400 --seed=42 --num_unique_classes_non_iid=1 --num_non_iid_users=1 --agg_type=fedla --sec_agg --use_approx_updates && \
python federated_main.py --dataset=emnist-balanced --epochs=100 --local_ep=10 --lr=0.01 --frac=0.7 --unequal --num_samples_per_user=2400 --seed=42 --num_unique_classes_non_iid=1 --num_non_iid_users=1 --agg_type=fedla --sec_agg --dropout=1 --first_dropout_epoch=1 --last_dropout_epoch=100 --use_approx_updates

# non-iid dataset, with k_r = 0.7, unique_c = 1, num_non_iid_users = 3
python federated_main.py --dataset=emnist-balanced --epochs=100 --local_ep=10 --lr=0.01 --frac=0.7 --unequal --num_samples_per_user=2400 --seed=42 --num_unique_classes_non_iid=1 --num_non_iid_users=3 --agg_type=fedla && \
python federated_main.py --dataset=emnist-balanced --epochs=100 --local_ep=10 --lr=0.01 --frac=0.7 --unequal --num_samples_per_user=2400 --seed=42 --num_unique_classes_non_iid=1 --num_non_iid_users=3 --agg_type=fedavg --fedavg_type=unweighted && \
python federated_main.py --dataset=emnist-balanced --epochs=100 --local_ep=10 --lr=0.01 --frac=0.7 --unequal --num_samples_per_user=2400 --seed=42 --num_unique_classes_non_iid=1 --num_non_iid_users=3 --agg_type=fedla --sec_agg --use_approx_updates && \
python federated_main.py --dataset=emnist-balanced --epochs=100 --local_ep=10 --lr=0.01 --frac=0.7 --unequal --num_samples_per_user=2400 --seed=42 --num_unique_classes_non_iid=1 --num_non_iid_users=3 --agg_type=fedla --sec_agg --dropout=1 --first_dropout_epoch=1 --last_dropout_epoch=100 --use_approx_updates

# non-iid dataset, with k_r = 0.7, unique_c = 1, num_non_iid_users = 5
python federated_main.py --dataset=emnist-balanced --epochs=100 --local_ep=10 --lr=0.01 --frac=0.7 --unequal --num_samples_per_user=2400 --seed=42 --num_unique_classes_non_iid=1 --num_non_iid_users=5 --agg_type=fedla && \
python federated_main.py --dataset=emnist-balanced --epochs=100 --local_ep=10 --lr=0.01 --frac=0.7 --unequal --num_samples_per_user=2400 --seed=42 --num_unique_classes_non_iid=1 --num_non_iid_users=5 --agg_type=fedavg --fedavg_type=unweighted && \
python federated_main.py --dataset=emnist-balanced --epochs=100 --local_ep=10 --lr=0.01 --frac=0.7 --unequal --num_samples_per_user=2400 --seed=42 --num_unique_classes_non_iid=1 --num_non_iid_users=5 --agg_type=fedla --sec_agg --use_approx_updates && \
python federated_main.py --dataset=emnist-balanced --epochs=100 --local_ep=10 --lr=0.01 --frac=0.7 --unequal --num_samples_per_user=2400 --seed=42 --num_unique_classes_non_iid=1 --num_non_iid_users=5 --agg_type=fedla --sec_agg --dropout=1 --first_dropout_epoch=1 --last_dropout_epoch=100 --use_approx_updates

# non-iid dataset, with k_r = 0.7, unique_c = 1, num_non_iid_users = 7
python federated_main.py --dataset=emnist-balanced --epochs=100 --local_ep=10 --lr=0.01 --frac=0.7 --unequal --num_samples_per_user=2400 --seed=42 --num_unique_classes_non_iid=1 --num_non_iid_users=7 --agg_type=fedla && \
python federated_main.py --dataset=emnist-balanced --epochs=100 --local_ep=10 --lr=0.01 --frac=0.7 --unequal --num_samples_per_user=2400 --seed=42 --num_unique_classes_non_iid=1 --num_non_iid_users=7 --agg_type=fedavg --fedavg_type=unweighted && \
python federated_main.py --dataset=emnist-balanced --epochs=100 --local_ep=10 --lr=0.01 --frac=0.7 --unequal --num_samples_per_user=2400 --seed=42 --num_unique_classes_non_iid=1 --num_non_iid_users=7 --agg_type=fedla --sec_agg --use_approx_updates && \
python federated_main.py --dataset=emnist-balanced --epochs=100 --local_ep=10 --lr=0.01 --frac=0.7 --unequal --num_samples_per_user=2400 --seed=42 --num_unique_classes_non_iid=1 --num_non_iid_users=7 --agg_type=fedla --sec_agg --dropout=1 --first_dropout_epoch=1 --last_dropout_epoch=100 --use_approx_updates

# non-iid dataset, with k_r = 0.8, unique_c = 1, num_non_iid_users = 7
python federated_main.py --dataset=emnist-balanced --epochs=100 --local_ep=10 --lr=0.01 --frac=0.8 --unequal --num_samples_per_user=2400 --seed=42 --num_unique_classes_non_iid=1 --num_non_iid_users=7 --agg_type=fedla && \
python federated_main.py --dataset=emnist-balanced --epochs=100 --local_ep=10 --lr=0.01 --frac=0.8 --unequal --num_samples_per_user=2400 --seed=42 --num_unique_classes_non_iid=1 --num_non_iid_users=7 --agg_type=fedavg --fedavg_type=unweighted && \
python federated_main.py --dataset=emnist-balanced --epochs=100 --local_ep=10 --lr=0.01 --frac=0.8 --unequal --num_samples_per_user=2400 --seed=42 --num_unique_classes_non_iid=1 --num_non_iid_users=7 --agg_type=fedla --sec_agg --use_approx_updates && \
python federated_main.py --dataset=emnist-balanced --epochs=100 --local_ep=10 --lr=0.01 --frac=0.8 --unequal --num_samples_per_user=2400 --seed=42 --num_unique_classes_non_iid=1 --num_non_iid_users=7 --agg_type=fedla --sec_agg --dropout=2 --first_dropout_epoch=1 --last_dropout_epoch=100 --use_approx_updates

# non-iid dataset, with k_r = 0.9, unique_c = 1, num_non_iid_users = 7
python federated_main.py --dataset=emnist-balanced --epochs=100 --local_ep=10 --lr=0.01 --frac=0.9 --unequal --num_samples_per_user=2400 --seed=42 --num_unique_classes_non_iid=1 --num_non_iid_users=7 --agg_type=fedla && \
python federated_main.py --dataset=emnist-balanced --epochs=100 --local_ep=10 --lr=0.01 --frac=0.9 --unequal --num_samples_per_user=2400 --seed=42 --num_unique_classes_non_iid=1 --num_non_iid_users=7 --agg_type=fedavg --fedavg_type=unweighted && \
python federated_main.py --dataset=emnist-balanced --epochs=100 --local_ep=10 --lr=0.01 --frac=0.9 --unequal --num_samples_per_user=2400 --seed=42 --num_unique_classes_non_iid=1 --num_non_iid_users=7 --agg_type=fedla --sec_agg --use_approx_updates && \
python federated_main.py --dataset=emnist-balanced --epochs=100 --local_ep=10 --lr=0.01 --frac=0.9 --unequal --num_samples_per_user=2400 --seed=42 --num_unique_classes_non_iid=1 --num_non_iid_users=7 --agg_type=fedla --sec_agg --dropout=3 --first_dropout_epoch=1 --last_dropout_epoch=100 --use_approx_updates

# non-iid dataset, with k_r = 1.0, unique_c = 1, num_non_iid_users = 7
python federated_main.py --dataset=emnist-balanced --epochs=100 --local_ep=10 --lr=0.01 --frac=1.0 --unequal --num_samples_per_user=2400 --seed=42 --num_unique_classes_non_iid=1 --num_non_iid_users=7 --agg_type=fedla && \
python federated_main.py --dataset=emnist-balanced --epochs=100 --local_ep=10 --lr=0.01 --frac=1.0 --unequal --num_samples_per_user=2400 --seed=42 --num_unique_classes_non_iid=1 --num_non_iid_users=7 --agg_type=fedavg --fedavg_type=unweighted && \
python federated_main.py --dataset=emnist-balanced --epochs=100 --local_ep=10 --lr=0.01 --frac=1.0 --unequal --num_samples_per_user=2400 --seed=42 --num_unique_classes_non_iid=1 --num_non_iid_users=7 --agg_type=fedla --sec_agg --use_approx_updates && \
python federated_main.py --dataset=emnist-balanced --epochs=100 --local_ep=10 --lr=0.01 --frac=1.0 --unequal --num_samples_per_user=2400 --seed=42 --num_unique_classes_non_iid=1 --num_non_iid_users=7 --agg_type=fedla --sec_agg --dropout=4 --first_dropout_epoch=1 --last_dropout_epoch=100 --use_approx_updates

# non-iid dataset, with k_r = 0.7, unique_c = 2, num_non_iid_users = 1
python federated_main.py --dataset=emnist-balanced --epochs=100 --local_ep=10 --lr=0.01 --frac=0.7 --unequal --num_samples_per_user=2400 --seed=42 --num_unique_classes_non_iid=2 --num_non_iid_users=1 --agg_type=fedla && \
python federated_main.py --dataset=emnist-balanced --epochs=100 --local_ep=10 --lr=0.01 --frac=0.7 --unequal --num_samples_per_user=2400 --seed=42 --num_unique_classes_non_iid=2 --num_non_iid_users=1 --agg_type=fedavg --fedavg_type=unweighted && \
python federated_main.py --dataset=emnist-balanced --epochs=100 --local_ep=10 --lr=0.01 --frac=0.7 --unequal --num_samples_per_user=2400 --seed=42 --num_unique_classes_non_iid=2 --num_non_iid_users=1 --agg_type=fedla --sec_agg --use_approx_updates && \
python federated_main.py --dataset=emnist-balanced --epochs=100 --local_ep=10 --lr=0.01 --frac=0.7 --unequal --num_samples_per_user=2400 --seed=42 --num_unique_classes_non_iid=2 --num_non_iid_users=1 --agg_type=fedla --sec_agg --dropout=1 --first_dropout_epoch=1 --last_dropout_epoch=100 --use_approx_updates

# non-iid dataset, with k_r = 0.7, unique_c = 2, num_non_iid_users = 3
python federated_main.py --dataset=emnist-balanced --epochs=100 --local_ep=10 --lr=0.01 --frac=0.7 --unequal --num_samples_per_user=2400 --seed=42 --num_unique_classes_non_iid=2 --num_non_iid_users=3 --agg_type=fedla && \
python federated_main.py --dataset=emnist-balanced --epochs=100 --local_ep=10 --lr=0.01 --frac=0.7 --unequal --num_samples_per_user=2400 --seed=42 --num_unique_classes_non_iid=2 --num_non_iid_users=3 --agg_type=fedavg --fedavg_type=unweighted && \
python federated_main.py --dataset=emnist-balanced --epochs=100 --local_ep=10 --lr=0.01 --frac=0.7 --unequal --num_samples_per_user=2400 --seed=42 --num_unique_classes_non_iid=2 --num_non_iid_users=3 --agg_type=fedla --sec_agg --use_approx_updates && \
python federated_main.py --dataset=emnist-balanced --epochs=100 --local_ep=10 --lr=0.01 --frac=0.7 --unequal --num_samples_per_user=2400 --seed=42 --num_unique_classes_non_iid=2 --num_non_iid_users=3 --agg_type=fedla --sec_agg --dropout=1 --first_dropout_epoch=1 --last_dropout_epoch=100 --use_approx_updates

# non-iid dataset, with k_r = 0.7, unique_c = 2, num_non_iid_users = 5
python federated_main.py --dataset=emnist-balanced --epochs=100 --local_ep=10 --lr=0.01 --frac=0.7 --unequal --num_samples_per_user=2400 --seed=42 --num_unique_classes_non_iid=2 --num_non_iid_users=5 --agg_type=fedla && \
python federated_main.py --dataset=emnist-balanced --epochs=100 --local_ep=10 --lr=0.01 --frac=0.7 --unequal --num_samples_per_user=2400 --seed=42 --num_unique_classes_non_iid=2 --num_non_iid_users=5 --agg_type=fedavg --fedavg_type=unweighted && \
python federated_main.py --dataset=emnist-balanced --epochs=100 --local_ep=10 --lr=0.01 --frac=0.7 --unequal --num_samples_per_user=2400 --seed=42 --num_unique_classes_non_iid=2 --num_non_iid_users=5 --agg_type=fedla --sec_agg --use_approx_updates && \
python federated_main.py --dataset=emnist-balanced --epochs=100 --local_ep=10 --lr=0.01 --frac=0.7 --unequal --num_samples_per_user=2400 --seed=42 --num_unique_classes_non_iid=2 --num_non_iid_users=5 --agg_type=fedla --sec_agg --dropout=1 --first_dropout_epoch=1 --last_dropout_epoch=100 --use_approx_updates

# non-iid dataset, with k_r = 0.7, unique_c = 2, num_non_iid_users = 7
python federated_main.py --dataset=emnist-balanced --epochs=100 --local_ep=10 --lr=0.01 --frac=0.7 --unequal --num_samples_per_user=2400 --seed=42 --num_unique_classes_non_iid=2 --num_non_iid_users=7 --agg_type=fedla && \
python federated_main.py --dataset=emnist-balanced --epochs=100 --local_ep=10 --lr=0.01 --frac=0.7 --unequal --num_samples_per_user=2400 --seed=42 --num_unique_classes_non_iid=2 --num_non_iid_users=7 --agg_type=fedavg --fedavg_type=unweighted && \
python federated_main.py --dataset=emnist-balanced --epochs=100 --local_ep=10 --lr=0.01 --frac=0.7 --unequal --num_samples_per_user=2400 --seed=42 --num_unique_classes_non_iid=2 --num_non_iid_users=7 --agg_type=fedla --sec_agg --use_approx_updates && \
python federated_main.py --dataset=emnist-balanced --epochs=100 --local_ep=10 --lr=0.01 --frac=0.7 --unequal --num_samples_per_user=2400 --seed=42 --num_unique_classes_non_iid=2 --num_non_iid_users=7 --agg_type=fedla --sec_agg --dropout=1 --first_dropout_epoch=1 --last_dropout_epoch=100 --use_approx_updates

# non-iid dataset, with k_r = 0.7, unique_c = 3, num_non_iid_users = 1
python federated_main.py --dataset=emnist-balanced --epochs=100 --local_ep=10 --lr=0.01 --frac=0.7 --unequal --num_samples_per_user=2400 --seed=42 --num_unique_classes_non_iid=3 --num_non_iid_users=1 --agg_type=fedla && \
python federated_main.py --dataset=emnist-balanced --epochs=100 --local_ep=10 --lr=0.01 --frac=0.7 --unequal --num_samples_per_user=2400 --seed=42 --num_unique_classes_non_iid=3 --num_non_iid_users=1 --agg_type=fedavg --fedavg_type=unweighted && \
python federated_main.py --dataset=emnist-balanced --epochs=100 --local_ep=10 --lr=0.01 --frac=0.7 --unequal --num_samples_per_user=2400 --seed=42 --num_unique_classes_non_iid=3 --num_non_iid_users=1 --agg_type=fedla --sec_agg --use_approx_updates && \
python federated_main.py --dataset=emnist-balanced --epochs=100 --local_ep=10 --lr=0.01 --frac=0.7 --unequal --num_samples_per_user=2400 --seed=42 --num_unique_classes_non_iid=3 --num_non_iid_users=1 --agg_type=fedla --sec_agg --dropout=1 --first_dropout_epoch=1 --last_dropout_epoch=100 --use_approx_updates

# non-iid dataset, with k_r = 0.7, unique_c = 3, num_non_iid_users = 3
python federated_main.py --dataset=emnist-balanced --epochs=100 --local_ep=10 --lr=0.01 --frac=0.7 --unequal --num_samples_per_user=2400 --seed=42 --num_unique_classes_non_iid=3 --num_non_iid_users=3 --agg_type=fedla && \
python federated_main.py --dataset=emnist-balanced --epochs=100 --local_ep=10 --lr=0.01 --frac=0.7 --unequal --num_samples_per_user=2400 --seed=42 --num_unique_classes_non_iid=3 --num_non_iid_users=3 --agg_type=fedavg --fedavg_type=unweighted && \
python federated_main.py --dataset=emnist-balanced --epochs=100 --local_ep=10 --lr=0.01 --frac=0.7 --unequal --num_samples_per_user=2400 --seed=42 --num_unique_classes_non_iid=3 --num_non_iid_users=3 --agg_type=fedla --sec_agg --use_approx_updates && \
python federated_main.py --dataset=emnist-balanced --epochs=100 --local_ep=10 --lr=0.01 --frac=0.7 --unequal --num_samples_per_user=2400 --seed=42 --num_unique_classes_non_iid=3 --num_non_iid_users=3 --agg_type=fedla --sec_agg --dropout=1 --first_dropout_epoch=1 --last_dropout_epoch=100 --use_approx_updates

# non-iid dataset, with k_r = 0.7, unique_c = 3, num_non_iid_users = 5
python federated_main.py --dataset=emnist-balanced --epochs=100 --local_ep=10 --lr=0.01 --frac=0.7 --unequal --num_samples_per_user=2400 --seed=42 --num_unique_classes_non_iid=3 --num_non_iid_users=5 --agg_type=fedla && \
python federated_main.py --dataset=emnist-balanced --epochs=100 --local_ep=10 --lr=0.01 --frac=0.7 --unequal --num_samples_per_user=2400 --seed=42 --num_unique_classes_non_iid=3 --num_non_iid_users=5 --agg_type=fedavg --fedavg_type=unweighted && \
python federated_main.py --dataset=emnist-balanced --epochs=100 --local_ep=10 --lr=0.01 --frac=0.7 --unequal --num_samples_per_user=2400 --seed=42 --num_unique_classes_non_iid=3 --num_non_iid_users=5 --agg_type=fedla --sec_agg --use_approx_updates && \
python federated_main.py --dataset=emnist-balanced --epochs=100 --local_ep=10 --lr=0.01 --frac=0.7 --unequal --num_samples_per_user=2400 --seed=42 --num_unique_classes_non_iid=3 --num_non_iid_users=5 --agg_type=fedla --sec_agg --dropout=1 --first_dropout_epoch=1 --last_dropout_epoch=100 --use_approx_updates

# non-iid dataset, with k_r = 0.7, unique_c = 3, num_non_iid_users = 7
python federated_main.py --dataset=emnist-balanced --epochs=100 --local_ep=10 --lr=0.01 --frac=0.7 --unequal --num_samples_per_user=2400 --seed=42 --num_unique_classes_non_iid=3 --num_non_iid_users=7 --agg_type=fedla && \
python federated_main.py --dataset=emnist-balanced --epochs=100 --local_ep=10 --lr=0.01 --frac=0.7 --unequal --num_samples_per_user=2400 --seed=42 --num_unique_classes_non_iid=3 --num_non_iid_users=7 --agg_type=fedavg --fedavg_type=unweighted && \
python federated_main.py --dataset=emnist-balanced --epochs=100 --local_ep=10 --lr=0.01 --frac=0.7 --unequal --num_samples_per_user=2400 --seed=42 --num_unique_classes_non_iid=3 --num_non_iid_users=7 --agg_type=fedla --sec_agg --use_approx_updates && \
python federated_main.py --dataset=emnist-balanced --epochs=100 --local_ep=10 --lr=0.01 --frac=0.7 --unequal --num_samples_per_user=2400 --seed=42 --num_unique_classes_non_iid=3 --num_non_iid_users=7 --agg_type=fedla --sec_agg --dropout=1 --first_dropout_epoch=1 --last_dropout_epoch=100 --use_approx_updates

# non-iid dataset, with k_r = 0.7, unique_c = 4, num_non_iid_users = 1
python federated_main.py --dataset=emnist-balanced --epochs=100 --local_ep=10 --lr=0.01 --frac=0.7 --unequal --num_samples_per_user=2400 --seed=42 --num_unique_classes_non_iid=4 --num_non_iid_users=1 --agg_type=fedla && \
python federated_main.py --dataset=emnist-balanced --epochs=100 --local_ep=10 --lr=0.01 --frac=0.7 --unequal --num_samples_per_user=2400 --seed=42 --num_unique_classes_non_iid=4 --num_non_iid_users=1 --agg_type=fedavg --fedavg_type=unweighted && \
python federated_main.py --dataset=emnist-balanced --epochs=100 --local_ep=10 --lr=0.01 --frac=0.7 --unequal --num_samples_per_user=2400 --seed=42 --num_unique_classes_non_iid=4 --num_non_iid_users=1 --agg_type=fedla --sec_agg --use_approx_updates && \
python federated_main.py --dataset=emnist-balanced --epochs=100 --local_ep=10 --lr=0.01 --frac=0.7 --unequal --num_samples_per_user=2400 --seed=42 --num_unique_classes_non_iid=4 --num_non_iid_users=1 --agg_type=fedla --sec_agg --dropout=1 --first_dropout_epoch=1 --last_dropout_epoch=100 --use_approx_updates

# non-iid dataset, with k_r = 0.7, unique_c = 4, num_non_iid_users = 3
python federated_main.py --dataset=emnist-balanced --epochs=100 --local_ep=10 --lr=0.01 --frac=0.7 --unequal --num_samples_per_user=2400 --seed=42 --num_unique_classes_non_iid=4 --num_non_iid_users=3 --agg_type=fedla && \
python federated_main.py --dataset=emnist-balanced --epochs=100 --local_ep=10 --lr=0.01 --frac=0.7 --unequal --num_samples_per_user=2400 --seed=42 --num_unique_classes_non_iid=4 --num_non_iid_users=3 --agg_type=fedavg --fedavg_type=unweighted && \
python federated_main.py --dataset=emnist-balanced --epochs=100 --local_ep=10 --lr=0.01 --frac=0.7 --unequal --num_samples_per_user=2400 --seed=42 --num_unique_classes_non_iid=4 --num_non_iid_users=3 --agg_type=fedla --sec_agg --use_approx_updates && \
python federated_main.py --dataset=emnist-balanced --epochs=100 --local_ep=10 --lr=0.01 --frac=0.7 --unequal --num_samples_per_user=2400 --seed=42 --num_unique_classes_non_iid=4 --num_non_iid_users=3 --agg_type=fedla --sec_agg --dropout=1 --first_dropout_epoch=1 --last_dropout_epoch=100 --use_approx_updates

# non-iid dataset, with k_r = 0.7, unique_c = 4, num_non_iid_users = 5
python federated_main.py --dataset=emnist-balanced --epochs=100 --local_ep=10 --lr=0.01 --frac=0.7 --unequal --num_samples_per_user=2400 --seed=42 --num_unique_classes_non_iid=4 --num_non_iid_users=5 --agg_type=fedla && \
python federated_main.py --dataset=emnist-balanced --epochs=100 --local_ep=10 --lr=0.01 --frac=0.7 --unequal --num_samples_per_user=2400 --seed=42 --num_unique_classes_non_iid=4 --num_non_iid_users=5 --agg_type=fedavg --fedavg_type=unweighted && \
python federated_main.py --dataset=emnist-balanced --epochs=100 --local_ep=10 --lr=0.01 --frac=0.7 --unequal --num_samples_per_user=2400 --seed=42 --num_unique_classes_non_iid=4 --num_non_iid_users=5 --agg_type=fedla --sec_agg --use_approx_updates && \
python federated_main.py --dataset=emnist-balanced --epochs=100 --local_ep=10 --lr=0.01 --frac=0.7 --unequal --num_samples_per_user=2400 --seed=42 --num_unique_classes_non_iid=4 --num_non_iid_users=5 --agg_type=fedla --sec_agg --dropout=1 --first_dropout_epoch=1 --last_dropout_epoch=100 --use_approx_updates

# non-iid dataset, with k_r = 0.7, unique_c = 4, num_non_iid_users = 7
python federated_main.py --dataset=emnist-balanced --epochs=100 --local_ep=10 --lr=0.01 --frac=0.7 --unequal --num_samples_per_user=2400 --seed=42 --num_unique_classes_non_iid=4 --num_non_iid_users=7 --agg_type=fedla && \
python federated_main.py --dataset=emnist-balanced --epochs=100 --local_ep=10 --lr=0.01 --frac=0.7 --unequal --num_samples_per_user=2400 --seed=42 --num_unique_classes_non_iid=4 --num_non_iid_users=7 --agg_type=fedavg --fedavg_type=unweighted && \
python federated_main.py --dataset=emnist-balanced --epochs=100 --local_ep=10 --lr=0.01 --frac=0.7 --unequal --num_samples_per_user=2400 --seed=42 --num_unique_classes_non_iid=4 --num_non_iid_users=7 --agg_type=fedla --sec_agg --use_approx_updates && \
python federated_main.py --dataset=emnist-balanced --epochs=100 --local_ep=10 --lr=0.01 --frac=0.7 --unequal --num_samples_per_user=2400 --seed=42 --num_unique_classes_non_iid=4 --num_non_iid_users=7 --agg_type=fedla --sec_agg --dropout=1 --first_dropout_epoch=1 --last_dropout_epoch=100 --use_approx_updates

# non-iid dataset, with k_r = 0.7, unique_c = 6, num_non_iid_users = 1
python federated_main.py --dataset=emnist-balanced --epochs=100 --local_ep=10 --lr=0.01 --frac=0.7 --unequal --num_samples_per_user=2400 --seed=42 --num_unique_classes_non_iid=6 --num_non_iid_users=1 --agg_type=fedla && \
python federated_main.py --dataset=emnist-balanced --epochs=100 --local_ep=10 --lr=0.01 --frac=0.7 --unequal --num_samples_per_user=2400 --seed=42 --num_unique_classes_non_iid=6 --num_non_iid_users=1 --agg_type=fedavg --fedavg_type=unweighted && \
python federated_main.py --dataset=emnist-balanced --epochs=100 --local_ep=10 --lr=0.01 --frac=0.7 --unequal --num_samples_per_user=2400 --seed=42 --num_unique_classes_non_iid=6 --num_non_iid_users=1 --agg_type=fedla --sec_agg --use_approx_updates && \
python federated_main.py --dataset=emnist-balanced --epochs=100 --local_ep=10 --lr=0.01 --frac=0.7 --unequal --num_samples_per_user=2400 --seed=42 --num_unique_classes_non_iid=6 --num_non_iid_users=1 --agg_type=fedla --sec_agg --dropout=1 --first_dropout_epoch=1 --last_dropout_epoch=100 --use_approx_updates

# non-iid dataset, with k_r = 0.7, unique_c = 6, num_non_iid_users = 3
python federated_main.py --dataset=emnist-balanced --epochs=100 --local_ep=10 --lr=0.01 --frac=0.7 --unequal --num_samples_per_user=2400 --seed=42 --num_unique_classes_non_iid=6 --num_non_iid_users=3 --agg_type=fedla && \
python federated_main.py --dataset=emnist-balanced --epochs=100 --local_ep=10 --lr=0.01 --frac=0.7 --unequal --num_samples_per_user=2400 --seed=42 --num_unique_classes_non_iid=6 --num_non_iid_users=3 --agg_type=fedavg --fedavg_type=unweighted && \
python federated_main.py --dataset=emnist-balanced --epochs=100 --local_ep=10 --lr=0.01 --frac=0.7 --unequal --num_samples_per_user=2400 --seed=42 --num_unique_classes_non_iid=6 --num_non_iid_users=3 --agg_type=fedla --sec_agg --use_approx_updates && \
python federated_main.py --dataset=emnist-balanced --epochs=100 --local_ep=10 --lr=0.01 --frac=0.7 --unequal --num_samples_per_user=2400 --seed=42 --num_unique_classes_non_iid=6 --num_non_iid_users=3 --agg_type=fedla --sec_agg --dropout=1 --first_dropout_epoch=1 --last_dropout_epoch=100 --use_approx_updates

# non-iid dataset, with k_r = 0.7, unique_c = 6, num_non_iid_users = 5
python federated_main.py --dataset=emnist-balanced --epochs=100 --local_ep=10 --lr=0.01 --frac=0.7 --unequal --num_samples_per_user=2400 --seed=42 --num_unique_classes_non_iid=6 --num_non_iid_users=5 --agg_type=fedla && \
python federated_main.py --dataset=emnist-balanced --epochs=100 --local_ep=10 --lr=0.01 --frac=0.7 --unequal --num_samples_per_user=2400 --seed=42 --num_unique_classes_non_iid=6 --num_non_iid_users=5 --agg_type=fedavg --fedavg_type=unweighted && \
python federated_main.py --dataset=emnist-balanced --epochs=100 --local_ep=10 --lr=0.01 --frac=0.7 --unequal --num_samples_per_user=2400 --seed=42 --num_unique_classes_non_iid=6 --num_non_iid_users=5 --agg_type=fedla --sec_agg --use_approx_updates && \
python federated_main.py --dataset=emnist-balanced --epochs=100 --local_ep=10 --lr=0.01 --frac=0.7 --unequal --num_samples_per_user=2400 --seed=42 --num_unique_classes_non_iid=6 --num_non_iid_users=5 --agg_type=fedla --sec_agg --dropout=1 --first_dropout_epoch=1 --last_dropout_epoch=100 --use_approx_updates

# non-iid dataset, with k_r = 0.7, unique_c = 6, num_non_iid_users = 7
python federated_main.py --dataset=emnist-balanced --epochs=100 --local_ep=10 --lr=0.01 --frac=0.7 --unequal --num_samples_per_user=2400 --seed=42 --num_unique_classes_non_iid=6 --num_non_iid_users=7 --agg_type=fedla && \
python federated_main.py --dataset=emnist-balanced --epochs=100 --local_ep=10 --lr=0.01 --frac=0.7 --unequal --num_samples_per_user=2400 --seed=42 --num_unique_classes_non_iid=6 --num_non_iid_users=7 --agg_type=fedavg --fedavg_type=unweighted && \
python federated_main.py --dataset=emnist-balanced --epochs=100 --local_ep=10 --lr=0.01 --frac=0.7 --unequal --num_samples_per_user=2400 --seed=42 --num_unique_classes_non_iid=6 --num_non_iid_users=7 --agg_type=fedla --sec_agg --use_approx_updates && \
python federated_main.py --dataset=emnist-balanced --epochs=100 --local_ep=10 --lr=0.01 --frac=0.7 --unequal --num_samples_per_user=2400 --seed=42 --num_unique_classes_non_iid=6 --num_non_iid_users=7 --agg_type=fedla --sec_agg --dropout=1 --first_dropout_epoch=1 --last_dropout_epoch=100 --use_approx_updates

# without use_approx_updates
python federated_main.py --dataset=emnist-balanced --epochs=100 --local_ep=10 --lr=0.01 --frac=0.7 --unequal --num_samples_per_user=2400 --seed=42 --num_unique_classes_non_iid=1 --num_non_iid_users=5 --agg_type=fedla --sec_agg && \
python federated_main.py --dataset=emnist-balanced --epochs=100 --local_ep=10 --lr=0.01 --frac=0.7 --unequal --num_samples_per_user=2400 --seed=42 --num_unique_classes_non_iid=1 --num_non_iid_users=5 --agg_type=fedla --sec_agg --dropout=1 --first_dropout_epoch=1 --last_dropout_epoch=100

# local dp C = 1.0, epsilon = 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.8, 1.0, 1.5
python federated_main.py --dataset=emnist-balanced --epochs=100 --local_ep=10 --lr=0.01 --frac=0.7 --unequal --num_samples_per_user=2400 --seed=42 --num_unique_classes_non_iid=1 --num_non_iid_users=7 --agg_type=fedla --sec_agg --use_approx_updates --local_dp --max_grad_norm=1.0 --iid_epsilon=0.1 --non_iid_epsilon=0.1 --delta=1e-5 && \
python federated_main.py --dataset=emnist-balanced --epochs=100 --local_ep=10 --lr=0.01 --frac=0.7 --unequal --num_samples_per_user=2400 --seed=42 --num_unique_classes_non_iid=1 --num_non_iid_users=7 --agg_type=fedla --sec_agg --use_approx_updates --local_dp --max_grad_norm=1.0 --iid_epsilon=0.2 --non_iid_epsilon=0.2 --delta=1e-5 && \
python federated_main.py --dataset=emnist-balanced --epochs=100 --local_ep=10 --lr=0.01 --frac=0.7 --unequal --num_samples_per_user=2400 --seed=42 --num_unique_classes_non_iid=1 --num_non_iid_users=7 --agg_type=fedla --sec_agg --use_approx_updates --local_dp --max_grad_norm=1.0 --iid_epsilon=0.3 --non_iid_epsilon=0.3 --delta=1e-5 && \
python federated_main.py --dataset=emnist-balanced --epochs=100 --local_ep=10 --lr=0.01 --frac=0.7 --unequal --num_samples_per_user=2400 --seed=42 --num_unique_classes_non_iid=1 --num_non_iid_users=7 --agg_type=fedla --sec_agg --use_approx_updates --local_dp --max_grad_norm=1.0 --iid_epsilon=0.4 --non_iid_epsilon=0.4 --delta=1e-5 && \
python federated_main.py --dataset=emnist-balanced --epochs=100 --local_ep=10 --lr=0.01 --frac=0.7 --unequal --num_samples_per_user=2400 --seed=42 --num_unique_classes_non_iid=1 --num_non_iid_users=7 --agg_type=fedla --sec_agg --use_approx_updates --local_dp --max_grad_norm=1.0 --iid_epsilon=0.5 --non_iid_epsilon=0.5 --delta=1e-5 && \
python federated_main.py --dataset=emnist-balanced --epochs=100 --local_ep=10 --lr=0.01 --frac=0.7 --unequal --num_samples_per_user=2400 --seed=42 --num_unique_classes_non_iid=1 --num_non_iid_users=7 --agg_type=fedla --sec_agg --use_approx_updates --local_dp --max_grad_norm=1.0 --iid_epsilon=0.6 --non_iid_epsilon=0.6 --delta=1e-5 && \
python federated_main.py --dataset=emnist-balanced --epochs=100 --local_ep=10 --lr=0.01 --frac=0.7 --unequal --num_samples_per_user=2400 --seed=42 --num_unique_classes_non_iid=1 --num_non_iid_users=7 --agg_type=fedla --sec_agg --use_approx_updates --local_dp --max_grad_norm=1.0 --iid_epsilon=0.8 --non_iid_epsilon=0.8 --delta=1e-5 && \
python federated_main.py --dataset=emnist-balanced --epochs=100 --local_ep=10 --lr=0.01 --frac=0.7 --unequal --num_samples_per_user=2400 --seed=42 --num_unique_classes_non_iid=1 --num_non_iid_users=7 --agg_type=fedla --sec_agg --use_approx_updates --local_dp --max_grad_norm=1.0 --iid_epsilon=1.0 --non_iid_epsilon=1.0 --delta=1e-5 && \
python federated_main.py --dataset=emnist-balanced --epochs=100 --local_ep=10 --lr=0.01 --frac=0.7 --unequal --num_samples_per_user=2400 --seed=42 --num_unique_classes_non_iid=1 --num_non_iid_users=7 --agg_type=fedla --sec_agg --use_approx_updates --local_dp --max_grad_norm=1.0 --iid_epsilon=1.5 --non_iid_epsilon=1.5 --delta=1e-5

# local dp C = 5.0, epsilon = 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.8, 1.0, 1.5
python federated_main.py --dataset=emnist-balanced --epochs=100 --local_ep=10 --lr=0.01 --frac=0.7 --unequal --num_samples_per_user=2400 --seed=42 --num_unique_classes_non_iid=1 --num_non_iid_users=7 --agg_type=fedla --sec_agg --use_approx_updates --local_dp --max_grad_norm=5.0 --iid_epsilon=0.1 --non_iid_epsilon=0.1 --delta=1e-5 && \
python federated_main.py --dataset=emnist-balanced --epochs=100 --local_ep=10 --lr=0.01 --frac=0.7 --unequal --num_samples_per_user=2400 --seed=42 --num_unique_classes_non_iid=1 --num_non_iid_users=7 --agg_type=fedla --sec_agg --use_approx_updates --local_dp --max_grad_norm=5.0 --iid_epsilon=0.2 --non_iid_epsilon=0.2 --delta=1e-5 && \
python federated_main.py --dataset=emnist-balanced --epochs=100 --local_ep=10 --lr=0.01 --frac=0.7 --unequal --num_samples_per_user=2400 --seed=42 --num_unique_classes_non_iid=1 --num_non_iid_users=7 --agg_type=fedla --sec_agg --use_approx_updates --local_dp --max_grad_norm=5.0 --iid_epsilon=0.3 --non_iid_epsilon=0.3 --delta=1e-5 && \
python federated_main.py --dataset=emnist-balanced --epochs=100 --local_ep=10 --lr=0.01 --frac=0.7 --unequal --num_samples_per_user=2400 --seed=42 --num_unique_classes_non_iid=1 --num_non_iid_users=7 --agg_type=fedla --sec_agg --use_approx_updates --local_dp --max_grad_norm=5.0 --iid_epsilon=0.4 --non_iid_epsilon=0.4 --delta=1e-5 && \
python federated_main.py --dataset=emnist-balanced --epochs=100 --local_ep=10 --lr=0.01 --frac=0.7 --unequal --num_samples_per_user=2400 --seed=42 --num_unique_classes_non_iid=1 --num_non_iid_users=7 --agg_type=fedla --sec_agg --use_approx_updates --local_dp --max_grad_norm=5.0 --iid_epsilon=0.5 --non_iid_epsilon=0.5 --delta=1e-5 && \
python federated_main.py --dataset=emnist-balanced --epochs=100 --local_ep=10 --lr=0.01 --frac=0.7 --unequal --num_samples_per_user=2400 --seed=42 --num_unique_classes_non_iid=1 --num_non_iid_users=7 --agg_type=fedla --sec_agg --use_approx_updates --local_dp --max_grad_norm=5.0 --iid_epsilon=0.6 --non_iid_epsilon=0.6 --delta=1e-5 && \
python federated_main.py --dataset=emnist-balanced --epochs=100 --local_ep=10 --lr=0.01 --frac=0.7 --unequal --num_samples_per_user=2400 --seed=42 --num_unique_classes_non_iid=1 --num_non_iid_users=7 --agg_type=fedla --sec_agg --use_approx_updates --local_dp --max_grad_norm=5.0 --iid_epsilon=0.8 --non_iid_epsilon=0.8 --delta=1e-5 && \
python federated_main.py --dataset=emnist-balanced --epochs=100 --local_ep=10 --lr=0.01 --frac=0.7 --unequal --num_samples_per_user=2400 --seed=42 --num_unique_classes_non_iid=1 --num_non_iid_users=7 --agg_type=fedla --sec_agg --use_approx_updates --local_dp --max_grad_norm=5.0 --iid_epsilon=1.0 --non_iid_epsilon=1.0 --delta=1e-5 && \
python federated_main.py --dataset=emnist-balanced --epochs=100 --local_ep=10 --lr=0.01 --frac=0.7 --unequal --num_samples_per_user=2400 --seed=42 --num_unique_classes_non_iid=1 --num_non_iid_users=7 --agg_type=fedla --sec_agg --use_approx_updates --local_dp --max_grad_norm=5.0 --iid_epsilon=1.5 --non_iid_epsilon=1.5 --delta=1e-5

# local dp C = 10.0, epsilon = 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.8, 1.0, 1.5
python federated_main.py --dataset=emnist-balanced --epochs=100 --local_ep=10 --lr=0.01 --frac=0.7 --unequal --num_samples_per_user=2400 --seed=42 --num_unique_classes_non_iid=1 --num_non_iid_users=7 --agg_type=fedla --sec_agg --use_approx_updates --local_dp --max_grad_norm=10.0 --iid_epsilon=0.1 --non_iid_epsilon=0.1 --delta=1e-5 && \
python federated_main.py --dataset=emnist-balanced --epochs=100 --local_ep=10 --lr=0.01 --frac=0.7 --unequal --num_samples_per_user=2400 --seed=42 --num_unique_classes_non_iid=1 --num_non_iid_users=7 --agg_type=fedla --sec_agg --use_approx_updates --local_dp --max_grad_norm=10.0 --iid_epsilon=0.2 --non_iid_epsilon=0.2 --delta=1e-5 && \
python federated_main.py --dataset=emnist-balanced --epochs=100 --local_ep=10 --lr=0.01 --frac=0.7 --unequal --num_samples_per_user=2400 --seed=42 --num_unique_classes_non_iid=1 --num_non_iid_users=7 --agg_type=fedla --sec_agg --use_approx_updates --local_dp --max_grad_norm=10.0 --iid_epsilon=0.3 --non_iid_epsilon=0.3 --delta=1e-5 && \
python federated_main.py --dataset=emnist-balanced --epochs=100 --local_ep=10 --lr=0.01 --frac=0.7 --unequal --num_samples_per_user=2400 --seed=42 --num_unique_classes_non_iid=1 --num_non_iid_users=7 --agg_type=fedla --sec_agg --use_approx_updates --local_dp --max_grad_norm=10.0 --iid_epsilon=0.4 --non_iid_epsilon=0.4 --delta=1e-5 && \
python federated_main.py --dataset=emnist-balanced --epochs=100 --local_ep=10 --lr=0.01 --frac=0.7 --unequal --num_samples_per_user=2400 --seed=42 --num_unique_classes_non_iid=1 --num_non_iid_users=7 --agg_type=fedla --sec_agg --use_approx_updates --local_dp --max_grad_norm=10.0 --iid_epsilon=0.5 --non_iid_epsilon=0.5 --delta=1e-5 && \
python federated_main.py --dataset=emnist-balanced --epochs=100 --local_ep=10 --lr=0.01 --frac=0.7 --unequal --num_samples_per_user=2400 --seed=42 --num_unique_classes_non_iid=1 --num_non_iid_users=7 --agg_type=fedla --sec_agg --use_approx_updates --local_dp --max_grad_norm=10.0 --iid_epsilon=0.6 --non_iid_epsilon=0.6 --delta=1e-5 && \
python federated_main.py --dataset=emnist-balanced --epochs=100 --local_ep=10 --lr=0.01 --frac=0.7 --unequal --num_samples_per_user=2400 --seed=42 --num_unique_classes_non_iid=1 --num_non_iid_users=7 --agg_type=fedla --sec_agg --use_approx_updates --local_dp --max_grad_norm=10.0 --iid_epsilon=0.8 --non_iid_epsilon=0.8 --delta=1e-5 && \
python federated_main.py --dataset=emnist-balanced --epochs=100 --local_ep=10 --lr=0.01 --frac=0.7 --unequal --num_samples_per_user=2400 --seed=42 --num_unique_classes_non_iid=1 --num_non_iid_users=7 --agg_type=fedla --sec_agg --use_approx_updates --local_dp --max_grad_norm=10.0 --iid_epsilon=1.0 --non_iid_epsilon=1.0 --delta=1e-5 && \
python federated_main.py --dataset=emnist-balanced --epochs=100 --local_ep=10 --lr=0.01 --frac=0.7 --unequal --num_samples_per_user=2400 --seed=42 --num_unique_classes_non_iid=1 --num_non_iid_users=7 --agg_type=fedla --sec_agg --use_approx_updates --local_dp --max_grad_norm=10.0 --iid_epsilon=1.5 --non_iid_epsilon=1.5 --delta=1e-5

# local dp C = 15.0, epsilon = 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.8, 1.0, 1.5
python federated_main.py --dataset=emnist-balanced --epochs=100 --local_ep=10 --lr=0.01 --frac=0.7 --unequal --num_samples_per_user=2400 --seed=42 --num_unique_classes_non_iid=1 --num_non_iid_users=7 --agg_type=fedla --sec_agg --use_approx_updates --local_dp --max_grad_norm=15.0 --iid_epsilon=0.1 --non_iid_epsilon=0.1 --delta=1e-5 && \
python federated_main.py --dataset=emnist-balanced --epochs=100 --local_ep=10 --lr=0.01 --frac=0.7 --unequal --num_samples_per_user=2400 --seed=42 --num_unique_classes_non_iid=1 --num_non_iid_users=7 --agg_type=fedla --sec_agg --use_approx_updates --local_dp --max_grad_norm=15.0 --iid_epsilon=0.2 --non_iid_epsilon=0.2 --delta=1e-5 && \
python federated_main.py --dataset=emnist-balanced --epochs=100 --local_ep=10 --lr=0.01 --frac=0.7 --unequal --num_samples_per_user=2400 --seed=42 --num_unique_classes_non_iid=1 --num_non_iid_users=7 --agg_type=fedla --sec_agg --use_approx_updates --local_dp --max_grad_norm=15.0 --iid_epsilon=0.3 --non_iid_epsilon=0.3 --delta=1e-5 && \
python federated_main.py --dataset=emnist-balanced --epochs=100 --local_ep=10 --lr=0.01 --frac=0.7 --unequal --num_samples_per_user=2400 --seed=42 --num_unique_classes_non_iid=1 --num_non_iid_users=7 --agg_type=fedla --sec_agg --use_approx_updates --local_dp --max_grad_norm=15.0 --iid_epsilon=0.4 --non_iid_epsilon=0.4 --delta=1e-5 && \
python federated_main.py --dataset=emnist-balanced --epochs=100 --local_ep=10 --lr=0.01 --frac=0.7 --unequal --num_samples_per_user=2400 --seed=42 --num_unique_classes_non_iid=1 --num_non_iid_users=7 --agg_type=fedla --sec_agg --use_approx_updates --local_dp --max_grad_norm=15.0 --iid_epsilon=0.5 --non_iid_epsilon=0.5 --delta=1e-5 && \
python federated_main.py --dataset=emnist-balanced --epochs=100 --local_ep=10 --lr=0.01 --frac=0.7 --unequal --num_samples_per_user=2400 --seed=42 --num_unique_classes_non_iid=1 --num_non_iid_users=7 --agg_type=fedla --sec_agg --use_approx_updates --local_dp --max_grad_norm=15.0 --iid_epsilon=0.6 --non_iid_epsilon=0.6 --delta=1e-5 && \
python federated_main.py --dataset=emnist-balanced --epochs=100 --local_ep=10 --lr=0.01 --frac=0.7 --unequal --num_samples_per_user=2400 --seed=42 --num_unique_classes_non_iid=1 --num_non_iid_users=7 --agg_type=fedla --sec_agg --use_approx_updates --local_dp --max_grad_norm=15.0 --iid_epsilon=0.8 --non_iid_epsilon=0.8 --delta=1e-5 && \
python federated_main.py --dataset=emnist-balanced --epochs=100 --local_ep=10 --lr=0.01 --frac=0.7 --unequal --num_samples_per_user=2400 --seed=42 --num_unique_classes_non_iid=1 --num_non_iid_users=7 --agg_type=fedla --sec_agg --use_approx_updates --local_dp --max_grad_norm=15.0 --iid_epsilon=1.0 --non_iid_epsilon=1.0 --delta=1e-5 && \
python federated_main.py --dataset=emnist-balanced --epochs=100 --local_ep=10 --lr=0.01 --frac=0.7 --unequal --num_samples_per_user=2400 --seed=42 --num_unique_classes_non_iid=1 --num_non_iid_users=7 --agg_type=fedla --sec_agg --use_approx_updates --local_dp --max_grad_norm=15.0 --iid_epsilon=1.5 --non_iid_epsilon=1.5 --delta=1e-5

# local dp C = 20.0, epsilon = 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.8, 1.0, 1.5
python federated_main.py --dataset=emnist-balanced --epochs=100 --local_ep=10 --lr=0.01 --frac=0.7 --unequal --num_samples_per_user=2400 --seed=42 --num_unique_classes_non_iid=1 --num_non_iid_users=7 --agg_type=fedla --sec_agg --use_approx_updates --local_dp --max_grad_norm=20.0 --iid_epsilon=0.1 --non_iid_epsilon=0.1 --delta=1e-5 && \
python federated_main.py --dataset=emnist-balanced --epochs=100 --local_ep=10 --lr=0.01 --frac=0.7 --unequal --num_samples_per_user=2400 --seed=42 --num_unique_classes_non_iid=1 --num_non_iid_users=7 --agg_type=fedla --sec_agg --use_approx_updates --local_dp --max_grad_norm=20.0 --iid_epsilon=0.2 --non_iid_epsilon=0.2 --delta=1e-5 && \
python federated_main.py --dataset=emnist-balanced --epochs=100 --local_ep=10 --lr=0.01 --frac=0.7 --unequal --num_samples_per_user=2400 --seed=42 --num_unique_classes_non_iid=1 --num_non_iid_users=7 --agg_type=fedla --sec_agg --use_approx_updates --local_dp --max_grad_norm=20.0 --iid_epsilon=0.3 --non_iid_epsilon=0.3 --delta=1e-5 && \
python federated_main.py --dataset=emnist-balanced --epochs=100 --local_ep=10 --lr=0.01 --frac=0.7 --unequal --num_samples_per_user=2400 --seed=42 --num_unique_classes_non_iid=1 --num_non_iid_users=7 --agg_type=fedla --sec_agg --use_approx_updates --local_dp --max_grad_norm=20.0 --iid_epsilon=0.4 --non_iid_epsilon=0.4 --delta=1e-5 && \
python federated_main.py --dataset=emnist-balanced --epochs=100 --local_ep=10 --lr=0.01 --frac=0.7 --unequal --num_samples_per_user=2400 --seed=42 --num_unique_classes_non_iid=1 --num_non_iid_users=7 --agg_type=fedla --sec_agg --use_approx_updates --local_dp --max_grad_norm=20.0 --iid_epsilon=0.5 --non_iid_epsilon=0.5 --delta=1e-5 && \
python federated_main.py --dataset=emnist-balanced --epochs=100 --local_ep=10 --lr=0.01 --frac=0.7 --unequal --num_samples_per_user=2400 --seed=42 --num_unique_classes_non_iid=1 --num_non_iid_users=7 --agg_type=fedla --sec_agg --use_approx_updates --local_dp --max_grad_norm=20.0 --iid_epsilon=0.6 --non_iid_epsilon=0.6 --delta=1e-5 && \
python federated_main.py --dataset=emnist-balanced --epochs=100 --local_ep=10 --lr=0.01 --frac=0.7 --unequal --num_samples_per_user=2400 --seed=42 --num_unique_classes_non_iid=1 --num_non_iid_users=7 --agg_type=fedla --sec_agg --use_approx_updates --local_dp --max_grad_norm=20.0 --iid_epsilon=0.8 --non_iid_epsilon=0.8 --delta=1e-5 && \
python federated_main.py --dataset=emnist-balanced --epochs=100 --local_ep=10 --lr=0.01 --frac=0.7 --unequal --num_samples_per_user=2400 --seed=42 --num_unique_classes_non_iid=1 --num_non_iid_users=7 --agg_type=fedla --sec_agg --use_approx_updates --local_dp --max_grad_norm=20.0 --iid_epsilon=1.0 --non_iid_epsilon=1.0 --delta=1e-5 && \
python federated_main.py --dataset=emnist-balanced --epochs=100 --local_ep=10 --lr=0.01 --frac=0.7 --unequal --num_samples_per_user=2400 --seed=42 --num_unique_classes_non_iid=1 --num_non_iid_users=7 --agg_type=fedla --sec_agg --use_approx_updates --local_dp --max_grad_norm=20.0 --iid_epsilon=1.5 --non_iid_epsilon=1.5 --delta=1e-5

# local dp C = 1.0, epsilon = 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.8, 1.0, 1.5, no SA
python federated_main.py --dataset=emnist-balanced --epochs=100 --local_ep=10 --lr=0.01 --frac=0.7 --unequal --num_samples_per_user=2400 --seed=42 --num_unique_classes_non_iid=1 --num_non_iid_users=7 --agg_type=fedla --local_dp --max_grad_norm=1.0 --iid_epsilon=0.1 --non_iid_epsilon=0.1 --delta=1e-5 && \
python federated_main.py --dataset=emnist-balanced --epochs=100 --local_ep=10 --lr=0.01 --frac=0.7 --unequal --num_samples_per_user=2400 --seed=42 --num_unique_classes_non_iid=1 --num_non_iid_users=7 --agg_type=fedla --local_dp --max_grad_norm=1.0 --iid_epsilon=0.2 --non_iid_epsilon=0.2 --delta=1e-5 && \
python federated_main.py --dataset=emnist-balanced --epochs=100 --local_ep=10 --lr=0.01 --frac=0.7 --unequal --num_samples_per_user=2400 --seed=42 --num_unique_classes_non_iid=1 --num_non_iid_users=7 --agg_type=fedla --local_dp --max_grad_norm=1.0 --iid_epsilon=0.3 --non_iid_epsilon=0.3 --delta=1e-5 && \
python federated_main.py --dataset=emnist-balanced --epochs=100 --local_ep=10 --lr=0.01 --frac=0.7 --unequal --num_samples_per_user=2400 --seed=42 --num_unique_classes_non_iid=1 --num_non_iid_users=7 --agg_type=fedla --local_dp --max_grad_norm=1.0 --iid_epsilon=0.4 --non_iid_epsilon=0.4 --delta=1e-5 && \
python federated_main.py --dataset=emnist-balanced --epochs=100 --local_ep=10 --lr=0.01 --frac=0.7 --unequal --num_samples_per_user=2400 --seed=42 --num_unique_classes_non_iid=1 --num_non_iid_users=7 --agg_type=fedla --local_dp --max_grad_norm=1.0 --iid_epsilon=0.5 --non_iid_epsilon=0.5 --delta=1e-5 && \
python federated_main.py --dataset=emnist-balanced --epochs=100 --local_ep=10 --lr=0.01 --frac=0.7 --unequal --num_samples_per_user=2400 --seed=42 --num_unique_classes_non_iid=1 --num_non_iid_users=7 --agg_type=fedla --local_dp --max_grad_norm=1.0 --iid_epsilon=0.6 --non_iid_epsilon=0.6 --delta=1e-5 && \
python federated_main.py --dataset=emnist-balanced --epochs=100 --local_ep=10 --lr=0.01 --frac=0.7 --unequal --num_samples_per_user=2400 --seed=42 --num_unique_classes_non_iid=1 --num_non_iid_users=7 --agg_type=fedla --local_dp --max_grad_norm=1.0 --iid_epsilon=0.8 --non_iid_epsilon=0.8 --delta=1e-5 && \
python federated_main.py --dataset=emnist-balanced --epochs=100 --local_ep=10 --lr=0.01 --frac=0.7 --unequal --num_samples_per_user=2400 --seed=42 --num_unique_classes_non_iid=1 --num_non_iid_users=7 --agg_type=fedla --local_dp --max_grad_norm=1.0 --iid_epsilon=1.0 --non_iid_epsilon=1.0 --delta=1e-5 && \
python federated_main.py --dataset=emnist-balanced --epochs=100 --local_ep=10 --lr=0.01 --frac=0.7 --unequal --num_samples_per_user=2400 --seed=42 --num_unique_classes_non_iid=1 --num_non_iid_users=7 --agg_type=fedla --local_dp --max_grad_norm=1.0 --iid_epsilon=1.5 --non_iid_epsilon=1.5 --delta=1e-5

# local dp C = 5.0, epsilon = 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.8, 1.0, 1.5, no SA
python federated_main.py --dataset=emnist-balanced --epochs=100 --local_ep=10 --lr=0.01 --frac=0.7 --unequal --num_samples_per_user=2400 --seed=42 --num_unique_classes_non_iid=1 --num_non_iid_users=7 --agg_type=fedla --local_dp --max_grad_norm=5.0 --iid_epsilon=0.1 --non_iid_epsilon=0.1 --delta=1e-5 && \
python federated_main.py --dataset=emnist-balanced --epochs=100 --local_ep=10 --lr=0.01 --frac=0.7 --unequal --num_samples_per_user=2400 --seed=42 --num_unique_classes_non_iid=1 --num_non_iid_users=7 --agg_type=fedla --local_dp --max_grad_norm=5.0 --iid_epsilon=0.2 --non_iid_epsilon=0.2 --delta=1e-5 && \
python federated_main.py --dataset=emnist-balanced --epochs=100 --local_ep=10 --lr=0.01 --frac=0.7 --unequal --num_samples_per_user=2400 --seed=42 --num_unique_classes_non_iid=1 --num_non_iid_users=7 --agg_type=fedla --local_dp --max_grad_norm=5.0 --iid_epsilon=0.3 --non_iid_epsilon=0.3 --delta=1e-5 && \
python federated_main.py --dataset=emnist-balanced --epochs=100 --local_ep=10 --lr=0.01 --frac=0.7 --unequal --num_samples_per_user=2400 --seed=42 --num_unique_classes_non_iid=1 --num_non_iid_users=7 --agg_type=fedla --local_dp --max_grad_norm=5.0 --iid_epsilon=0.4 --non_iid_epsilon=0.4 --delta=1e-5 && \
python federated_main.py --dataset=emnist-balanced --epochs=100 --local_ep=10 --lr=0.01 --frac=0.7 --unequal --num_samples_per_user=2400 --seed=42 --num_unique_classes_non_iid=1 --num_non_iid_users=7 --agg_type=fedla --local_dp --max_grad_norm=5.0 --iid_epsilon=0.5 --non_iid_epsilon=0.5 --delta=1e-5 && \
python federated_main.py --dataset=emnist-balanced --epochs=100 --local_ep=10 --lr=0.01 --frac=0.7 --unequal --num_samples_per_user=2400 --seed=42 --num_unique_classes_non_iid=1 --num_non_iid_users=7 --agg_type=fedla --local_dp --max_grad_norm=5.0 --iid_epsilon=0.6 --non_iid_epsilon=0.6 --delta=1e-5 && \
python federated_main.py --dataset=emnist-balanced --epochs=100 --local_ep=10 --lr=0.01 --frac=0.7 --unequal --num_samples_per_user=2400 --seed=42 --num_unique_classes_non_iid=1 --num_non_iid_users=7 --agg_type=fedla --local_dp --max_grad_norm=5.0 --iid_epsilon=0.8 --non_iid_epsilon=0.8 --delta=1e-5 && \
python federated_main.py --dataset=emnist-balanced --epochs=100 --local_ep=10 --lr=0.01 --frac=0.7 --unequal --num_samples_per_user=2400 --seed=42 --num_unique_classes_non_iid=1 --num_non_iid_users=7 --agg_type=fedla --local_dp --max_grad_norm=5.0 --iid_epsilon=1.0 --non_iid_epsilon=1.0 --delta=1e-5 && \
python federated_main.py --dataset=emnist-balanced --epochs=100 --local_ep=10 --lr=0.01 --frac=0.7 --unequal --num_samples_per_user=2400 --seed=42 --num_unique_classes_non_iid=1 --num_non_iid_users=7 --agg_type=fedla --local_dp --max_grad_norm=5.0 --iid_epsilon=1.5 --non_iid_epsilon=1.5 --delta=1e-5

# local dp C = 10.0, epsilon = 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.8, 1.0, 1.5, no SA
python federated_main.py --dataset=emnist-balanced --epochs=100 --local_ep=10 --lr=0.01 --frac=0.7 --unequal --num_samples_per_user=2400 --seed=42 --num_unique_classes_non_iid=1 --num_non_iid_users=7 --agg_type=fedla --local_dp --max_grad_norm=10.0 --iid_epsilon=0.1 --non_iid_epsilon=0.1 --delta=1e-5 && \
python federated_main.py --dataset=emnist-balanced --epochs=100 --local_ep=10 --lr=0.01 --frac=0.7 --unequal --num_samples_per_user=2400 --seed=42 --num_unique_classes_non_iid=1 --num_non_iid_users=7 --agg_type=fedla --local_dp --max_grad_norm=10.0 --iid_epsilon=0.2 --non_iid_epsilon=0.2 --delta=1e-5 && \
python federated_main.py --dataset=emnist-balanced --epochs=100 --local_ep=10 --lr=0.01 --frac=0.7 --unequal --num_samples_per_user=2400 --seed=42 --num_unique_classes_non_iid=1 --num_non_iid_users=7 --agg_type=fedla --local_dp --max_grad_norm=10.0 --iid_epsilon=0.3 --non_iid_epsilon=0.3 --delta=1e-5 && \
python federated_main.py --dataset=emnist-balanced --epochs=100 --local_ep=10 --lr=0.01 --frac=0.7 --unequal --num_samples_per_user=2400 --seed=42 --num_unique_classes_non_iid=1 --num_non_iid_users=7 --agg_type=fedla --local_dp --max_grad_norm=10.0 --iid_epsilon=0.4 --non_iid_epsilon=0.4 --delta=1e-5 && \
python federated_main.py --dataset=emnist-balanced --epochs=100 --local_ep=10 --lr=0.01 --frac=0.7 --unequal --num_samples_per_user=2400 --seed=42 --num_unique_classes_non_iid=1 --num_non_iid_users=7 --agg_type=fedla --local_dp --max_grad_norm=10.0 --iid_epsilon=0.5 --non_iid_epsilon=0.5 --delta=1e-5 && \
python federated_main.py --dataset=emnist-balanced --epochs=100 --local_ep=10 --lr=0.01 --frac=0.7 --unequal --num_samples_per_user=2400 --seed=42 --num_unique_classes_non_iid=1 --num_non_iid_users=7 --agg_type=fedla --local_dp --max_grad_norm=10.0 --iid_epsilon=0.6 --non_iid_epsilon=0.6 --delta=1e-5 && \
python federated_main.py --dataset=emnist-balanced --epochs=100 --local_ep=10 --lr=0.01 --frac=0.7 --unequal --num_samples_per_user=2400 --seed=42 --num_unique_classes_non_iid=1 --num_non_iid_users=7 --agg_type=fedla --local_dp --max_grad_norm=10.0 --iid_epsilon=0.8 --non_iid_epsilon=0.8 --delta=1e-5 && \
python federated_main.py --dataset=emnist-balanced --epochs=100 --local_ep=10 --lr=0.01 --frac=0.7 --unequal --num_samples_per_user=2400 --seed=42 --num_unique_classes_non_iid=1 --num_non_iid_users=7 --agg_type=fedla --local_dp --max_grad_norm=10.0 --iid_epsilon=1.0 --non_iid_epsilon=1.0 --delta=1e-5 && \
python federated_main.py --dataset=emnist-balanced --epochs=100 --local_ep=10 --lr=0.01 --frac=0.7 --unequal --num_samples_per_user=2400 --seed=42 --num_unique_classes_non_iid=1 --num_non_iid_users=7 --agg_type=fedla --local_dp --max_grad_norm=10.0 --iid_epsilon=1.5 --non_iid_epsilon=1.5 --delta=1e-5

# local dp C = 15.0, epsilon = 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.8, 1.0, 1.5, no SA
python federated_main.py --dataset=emnist-balanced --epochs=100 --local_ep=10 --lr=0.01 --frac=0.7 --unequal --num_samples_per_user=2400 --seed=42 --num_unique_classes_non_iid=1 --num_non_iid_users=7 --agg_type=fedla --local_dp --max_grad_norm=15.0 --iid_epsilon=0.1 --non_iid_epsilon=0.1 --delta=1e-5 && \
python federated_main.py --dataset=emnist-balanced --epochs=100 --local_ep=10 --lr=0.01 --frac=0.7 --unequal --num_samples_per_user=2400 --seed=42 --num_unique_classes_non_iid=1 --num_non_iid_users=7 --agg_type=fedla --local_dp --max_grad_norm=15.0 --iid_epsilon=0.2 --non_iid_epsilon=0.2 --delta=1e-5 && \
python federated_main.py --dataset=emnist-balanced --epochs=100 --local_ep=10 --lr=0.01 --frac=0.7 --unequal --num_samples_per_user=2400 --seed=42 --num_unique_classes_non_iid=1 --num_non_iid_users=7 --agg_type=fedla --local_dp --max_grad_norm=15.0 --iid_epsilon=0.3 --non_iid_epsilon=0.3 --delta=1e-5 && \
python federated_main.py --dataset=emnist-balanced --epochs=100 --local_ep=10 --lr=0.01 --frac=0.7 --unequal --num_samples_per_user=2400 --seed=42 --num_unique_classes_non_iid=1 --num_non_iid_users=7 --agg_type=fedla --local_dp --max_grad_norm=15.0 --iid_epsilon=0.4 --non_iid_epsilon=0.4 --delta=1e-5 && \
python federated_main.py --dataset=emnist-balanced --epochs=100 --local_ep=10 --lr=0.01 --frac=0.7 --unequal --num_samples_per_user=2400 --seed=42 --num_unique_classes_non_iid=1 --num_non_iid_users=7 --agg_type=fedla --local_dp --max_grad_norm=15.0 --iid_epsilon=0.5 --non_iid_epsilon=0.5 --delta=1e-5 && \
python federated_main.py --dataset=emnist-balanced --epochs=100 --local_ep=10 --lr=0.01 --frac=0.7 --unequal --num_samples_per_user=2400 --seed=42 --num_unique_classes_non_iid=1 --num_non_iid_users=7 --agg_type=fedla --local_dp --max_grad_norm=15.0 --iid_epsilon=0.6 --non_iid_epsilon=0.6 --delta=1e-5 && \
python federated_main.py --dataset=emnist-balanced --epochs=100 --local_ep=10 --lr=0.01 --frac=0.7 --unequal --num_samples_per_user=2400 --seed=42 --num_unique_classes_non_iid=1 --num_non_iid_users=7 --agg_type=fedla --local_dp --max_grad_norm=15.0 --iid_epsilon=0.8 --non_iid_epsilon=0.8 --delta=1e-5 && \
python federated_main.py --dataset=emnist-balanced --epochs=100 --local_ep=10 --lr=0.01 --frac=0.7 --unequal --num_samples_per_user=2400 --seed=42 --num_unique_classes_non_iid=1 --num_non_iid_users=7 --agg_type=fedla --local_dp --max_grad_norm=15.0 --iid_epsilon=1.0 --non_iid_epsilon=1.0 --delta=1e-5 && \
python federated_main.py --dataset=emnist-balanced --epochs=100 --local_ep=10 --lr=0.01 --frac=0.7 --unequal --num_samples_per_user=2400 --seed=42 --num_unique_classes_non_iid=1 --num_non_iid_users=7 --agg_type=fedla --local_dp --max_grad_norm=15.0 --iid_epsilon=1.5 --non_iid_epsilon=1.5 --delta=1e-5

# local dp C = 20.0, epsilon = 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.8, 1.0, 1.5, no SA
python federated_main.py --dataset=emnist-balanced --epochs=100 --local_ep=10 --lr=0.01 --frac=0.7 --unequal --num_samples_per_user=2400 --seed=42 --num_unique_classes_non_iid=1 --num_non_iid_users=7 --agg_type=fedla --local_dp --max_grad_norm=20.0 --iid_epsilon=0.1 --non_iid_epsilon=0.1 --delta=1e-5 && \
python federated_main.py --dataset=emnist-balanced --epochs=100 --local_ep=10 --lr=0.01 --frac=0.7 --unequal --num_samples_per_user=2400 --seed=42 --num_unique_classes_non_iid=1 --num_non_iid_users=7 --agg_type=fedla --local_dp --max_grad_norm=20.0 --iid_epsilon=0.2 --non_iid_epsilon=0.2 --delta=1e-5 && \
python federated_main.py --dataset=emnist-balanced --epochs=100 --local_ep=10 --lr=0.01 --frac=0.7 --unequal --num_samples_per_user=2400 --seed=42 --num_unique_classes_non_iid=1 --num_non_iid_users=7 --agg_type=fedla --local_dp --max_grad_norm=20.0 --iid_epsilon=0.3 --non_iid_epsilon=0.3 --delta=1e-5 && \
python federated_main.py --dataset=emnist-balanced --epochs=100 --local_ep=10 --lr=0.01 --frac=0.7 --unequal --num_samples_per_user=2400 --seed=42 --num_unique_classes_non_iid=1 --num_non_iid_users=7 --agg_type=fedla --local_dp --max_grad_norm=20.0 --iid_epsilon=0.4 --non_iid_epsilon=0.4 --delta=1e-5 && \
python federated_main.py --dataset=emnist-balanced --epochs=100 --local_ep=10 --lr=0.01 --frac=0.7 --unequal --num_samples_per_user=2400 --seed=42 --num_unique_classes_non_iid=1 --num_non_iid_users=7 --agg_type=fedla --local_dp --max_grad_norm=20.0 --iid_epsilon=0.5 --non_iid_epsilon=0.5 --delta=1e-5 && \
python federated_main.py --dataset=emnist-balanced --epochs=100 --local_ep=10 --lr=0.01 --frac=0.7 --unequal --num_samples_per_user=2400 --seed=42 --num_unique_classes_non_iid=1 --num_non_iid_users=7 --agg_type=fedla --local_dp --max_grad_norm=20.0 --iid_epsilon=0.6 --non_iid_epsilon=0.6 --delta=1e-5 && \
python federated_main.py --dataset=emnist-balanced --epochs=100 --local_ep=10 --lr=0.01 --frac=0.7 --unequal --num_samples_per_user=2400 --seed=42 --num_unique_classes_non_iid=1 --num_non_iid_users=7 --agg_type=fedla --local_dp --max_grad_norm=20.0 --iid_epsilon=0.8 --non_iid_epsilon=0.8 --delta=1e-5 && \
python federated_main.py --dataset=emnist-balanced --epochs=100 --local_ep=10 --lr=0.01 --frac=0.7 --unequal --num_samples_per_user=2400 --seed=42 --num_unique_classes_non_iid=1 --num_non_iid_users=7 --agg_type=fedla --local_dp --max_grad_norm=20.0 --iid_epsilon=1.0 --non_iid_epsilon=1.0 --delta=1e-5 && \
python federated_main.py --dataset=emnist-balanced --epochs=100 --local_ep=10 --lr=0.01 --frac=0.7 --unequal --num_samples_per_user=2400 --seed=42 --num_unique_classes_non_iid=1 --num_non_iid_users=7 --agg_type=fedla --local_dp --max_grad_norm=20.0 --iid_epsilon=1.5 --non_iid_epsilon=1.5 --delta=1e-5

# local dp C = 5.0, epsilon = 0.4, 0.5, 0.6, 0.8, 1.0, 1.5, no SA
python federated_main.py --dataset=emnist-balanced --epochs=100 --local_ep=10 --lr=0.01 --frac=0.7 --unequal --num_samples_per_user=2400 --seed=42 --num_unique_classes_non_iid=1 --num_non_iid_users=7 --agg_type=fedla --sec_agg --use_approx_updates --dropout=1 --first_dropout_epoch=1 --last_dropout_epoch=100 --local_dp --max_grad_norm=5.0 --iid_epsilon=0.4 --non_iid_epsilon=0.4 --delta=1e-5 && \
python federated_main.py --dataset=emnist-balanced --epochs=100 --local_ep=10 --lr=0.01 --frac=0.7 --unequal --num_samples_per_user=2400 --seed=42 --num_unique_classes_non_iid=1 --num_non_iid_users=7 --agg_type=fedla --sec_agg --use_approx_updates --dropout=1 --first_dropout_epoch=1 --last_dropout_epoch=100 --local_dp --max_grad_norm=5.0 --iid_epsilon=0.5 --non_iid_epsilon=0.5 --delta=1e-5 && \
python federated_main.py --dataset=emnist-balanced --epochs=100 --local_ep=10 --lr=0.01 --frac=0.7 --unequal --num_samples_per_user=2400 --seed=42 --num_unique_classes_non_iid=1 --num_non_iid_users=7 --agg_type=fedla --sec_agg --use_approx_updates --dropout=1 --first_dropout_epoch=1 --last_dropout_epoch=100 --local_dp --max_grad_norm=5.0 --iid_epsilon=0.6 --non_iid_epsilon=0.6 --delta=1e-5 && \
python federated_main.py --dataset=emnist-balanced --epochs=100 --local_ep=10 --lr=0.01 --frac=0.7 --unequal --num_samples_per_user=2400 --seed=42 --num_unique_classes_non_iid=1 --num_non_iid_users=7 --agg_type=fedla --sec_agg --use_approx_updates --dropout=1 --first_dropout_epoch=1 --last_dropout_epoch=100 --local_dp --max_grad_norm=5.0 --iid_epsilon=0.8 --non_iid_epsilon=0.8 --delta=1e-5 && \
python federated_main.py --dataset=emnist-balanced --epochs=100 --local_ep=10 --lr=0.01 --frac=0.7 --unequal --num_samples_per_user=2400 --seed=42 --num_unique_classes_non_iid=1 --num_non_iid_users=7 --agg_type=fedla --sec_agg --use_approx_updates --dropout=1 --first_dropout_epoch=1 --last_dropout_epoch=100 --local_dp --max_grad_norm=5.0 --iid_epsilon=1.0 --non_iid_epsilon=1.0 --delta=1e-5 && \
python federated_main.py --dataset=emnist-balanced --epochs=100 --local_ep=10 --lr=0.01 --frac=0.7 --unequal --num_samples_per_user=2400 --seed=42 --num_unique_classes_non_iid=1 --num_non_iid_users=7 --agg_type=fedla --sec_agg --use_approx_updates --dropout=1 --first_dropout_epoch=1 --last_dropout_epoch=100 --local_dp --max_grad_norm=5.0 --iid_epsilon=1.5 --non_iid_epsilon=1.5 --delta=1e-5

# local dp C = 6.0, epsilon = 0.4, 0.5, 0.6, 0.8, 1.0, 1.5, no SA
python federated_main.py --dataset=emnist-balanced --epochs=100 --local_ep=10 --lr=0.01 --frac=0.7 --unequal --num_samples_per_user=2400 --seed=42 --num_unique_classes_non_iid=1 --num_non_iid_users=7 --agg_type=fedla --sec_agg --use_approx_updates --dropout=1 --first_dropout_epoch=1 --last_dropout_epoch=100 --local_dp --max_grad_norm=6.0 --iid_epsilon=0.4 --non_iid_epsilon=0.4 --delta=1e-5 && \
python federated_main.py --dataset=emnist-balanced --epochs=100 --local_ep=10 --lr=0.01 --frac=0.7 --unequal --num_samples_per_user=2400 --seed=42 --num_unique_classes_non_iid=1 --num_non_iid_users=7 --agg_type=fedla --sec_agg --use_approx_updates --dropout=1 --first_dropout_epoch=1 --last_dropout_epoch=100 --local_dp --max_grad_norm=6.0 --iid_epsilon=0.5 --non_iid_epsilon=0.5 --delta=1e-5 && \
python federated_main.py --dataset=emnist-balanced --epochs=100 --local_ep=10 --lr=0.01 --frac=0.7 --unequal --num_samples_per_user=2400 --seed=42 --num_unique_classes_non_iid=1 --num_non_iid_users=7 --agg_type=fedla --sec_agg --use_approx_updates --dropout=1 --first_dropout_epoch=1 --last_dropout_epoch=100 --local_dp --max_grad_norm=6.0 --iid_epsilon=0.6 --non_iid_epsilon=0.6 --delta=1e-5 && \
python federated_main.py --dataset=emnist-balanced --epochs=100 --local_ep=10 --lr=0.01 --frac=0.7 --unequal --num_samples_per_user=2400 --seed=42 --num_unique_classes_non_iid=1 --num_non_iid_users=7 --agg_type=fedla --sec_agg --use_approx_updates --dropout=1 --first_dropout_epoch=1 --last_dropout_epoch=100 --local_dp --max_grad_norm=6.0 --iid_epsilon=0.8 --non_iid_epsilon=0.8 --delta=1e-5 && \
python federated_main.py --dataset=emnist-balanced --epochs=100 --local_ep=10 --lr=0.01 --frac=0.7 --unequal --num_samples_per_user=2400 --seed=42 --num_unique_classes_non_iid=1 --num_non_iid_users=7 --agg_type=fedla --sec_agg --use_approx_updates --dropout=1 --first_dropout_epoch=1 --last_dropout_epoch=100 --local_dp --max_grad_norm=6.0 --iid_epsilon=1.0 --non_iid_epsilon=1.0 --delta=1e-5 && \
python federated_main.py --dataset=emnist-balanced --epochs=100 --local_ep=10 --lr=0.01 --frac=0.7 --unequal --num_samples_per_user=2400 --seed=42 --num_unique_classes_non_iid=1 --num_non_iid_users=7 --agg_type=fedla --sec_agg --use_approx_updates --dropout=1 --first_dropout_epoch=1 --last_dropout_epoch=100 --local_dp --max_grad_norm=6.0 --iid_epsilon=1.5 --non_iid_epsilon=1.5 --delta=1e-5

# local dp C = 7.0, epsilon = 0.4, 0.5, 0.6, 0.8, 1.0, 1.5, no SA
python federated_main.py --dataset=emnist-balanced --epochs=100 --local_ep=10 --lr=0.01 --frac=0.7 --unequal --num_samples_per_user=2400 --seed=42 --num_unique_classes_non_iid=1 --num_non_iid_users=7 --agg_type=fedla --sec_agg --use_approx_updates --dropout=1 --first_dropout_epoch=1 --last_dropout_epoch=100 --local_dp --max_grad_norm=7.0 --iid_epsilon=0.4 --non_iid_epsilon=0.4 --delta=1e-5 && \
python federated_main.py --dataset=emnist-balanced --epochs=100 --local_ep=10 --lr=0.01 --frac=0.7 --unequal --num_samples_per_user=2400 --seed=42 --num_unique_classes_non_iid=1 --num_non_iid_users=7 --agg_type=fedla --sec_agg --use_approx_updates --dropout=1 --first_dropout_epoch=1 --last_dropout_epoch=100 --local_dp --max_grad_norm=7.0 --iid_epsilon=0.5 --non_iid_epsilon=0.5 --delta=1e-5 && \
python federated_main.py --dataset=emnist-balanced --epochs=100 --local_ep=10 --lr=0.01 --frac=0.7 --unequal --num_samples_per_user=2400 --seed=42 --num_unique_classes_non_iid=1 --num_non_iid_users=7 --agg_type=fedla --sec_agg --use_approx_updates --dropout=1 --first_dropout_epoch=1 --last_dropout_epoch=100 --local_dp --max_grad_norm=7.0 --iid_epsilon=0.6 --non_iid_epsilon=0.6 --delta=1e-5 && \
python federated_main.py --dataset=emnist-balanced --epochs=100 --local_ep=10 --lr=0.01 --frac=0.7 --unequal --num_samples_per_user=2400 --seed=42 --num_unique_classes_non_iid=1 --num_non_iid_users=7 --agg_type=fedla --sec_agg --use_approx_updates --dropout=1 --first_dropout_epoch=1 --last_dropout_epoch=100 --local_dp --max_grad_norm=7.0 --iid_epsilon=0.8 --non_iid_epsilon=0.8 --delta=1e-5 && \
python federated_main.py --dataset=emnist-balanced --epochs=100 --local_ep=10 --lr=0.01 --frac=0.7 --unequal --num_samples_per_user=2400 --seed=42 --num_unique_classes_non_iid=1 --num_non_iid_users=7 --agg_type=fedla --sec_agg --use_approx_updates --dropout=1 --first_dropout_epoch=1 --last_dropout_epoch=100 --local_dp --max_grad_norm=7.0 --iid_epsilon=1.0 --non_iid_epsilon=1.0 --delta=1e-5 && \
python federated_main.py --dataset=emnist-balanced --epochs=100 --local_ep=10 --lr=0.01 --frac=0.7 --unequal --num_samples_per_user=2400 --seed=42 --num_unique_classes_non_iid=1 --num_non_iid_users=7 --agg_type=fedla --sec_agg --use_approx_updates --dropout=1 --first_dropout_epoch=1 --last_dropout_epoch=100 --local_dp --max_grad_norm=7.0 --iid_epsilon=1.5 --non_iid_epsilon=1.5 --delta=1e-5

# local dp C = 8.0, epsilon = 0.4, 0.5, 0.6, 0.8, 1.0, 1.5, no SA
python federated_main.py --dataset=emnist-balanced --epochs=100 --local_ep=10 --lr=0.01 --frac=0.7 --unequal --num_samples_per_user=2400 --seed=42 --num_unique_classes_non_iid=1 --num_non_iid_users=7 --agg_type=fedla --sec_agg --use_approx_updates --dropout=1 --first_dropout_epoch=1 --last_dropout_epoch=100 --local_dp --max_grad_norm=8.0 --iid_epsilon=0.4 --non_iid_epsilon=0.4 --delta=1e-5 && \
python federated_main.py --dataset=emnist-balanced --epochs=100 --local_ep=10 --lr=0.01 --frac=0.7 --unequal --num_samples_per_user=2400 --seed=42 --num_unique_classes_non_iid=1 --num_non_iid_users=7 --agg_type=fedla --sec_agg --use_approx_updates --dropout=1 --first_dropout_epoch=1 --last_dropout_epoch=100 --local_dp --max_grad_norm=8.0 --iid_epsilon=0.5 --non_iid_epsilon=0.5 --delta=1e-5 && \
python federated_main.py --dataset=emnist-balanced --epochs=100 --local_ep=10 --lr=0.01 --frac=0.7 --unequal --num_samples_per_user=2400 --seed=42 --num_unique_classes_non_iid=1 --num_non_iid_users=7 --agg_type=fedla --sec_agg --use_approx_updates --dropout=1 --first_dropout_epoch=1 --last_dropout_epoch=100 --local_dp --max_grad_norm=8.0 --iid_epsilon=0.6 --non_iid_epsilon=0.6 --delta=1e-5 && \
python federated_main.py --dataset=emnist-balanced --epochs=100 --local_ep=10 --lr=0.01 --frac=0.7 --unequal --num_samples_per_user=2400 --seed=42 --num_unique_classes_non_iid=1 --num_non_iid_users=7 --agg_type=fedla --sec_agg --use_approx_updates --dropout=1 --first_dropout_epoch=1 --last_dropout_epoch=100 --local_dp --max_grad_norm=8.0 --iid_epsilon=0.8 --non_iid_epsilon=0.8 --delta=1e-5 && \
python federated_main.py --dataset=emnist-balanced --epochs=100 --local_ep=10 --lr=0.01 --frac=0.7 --unequal --num_samples_per_user=2400 --seed=42 --num_unique_classes_non_iid=1 --num_non_iid_users=7 --agg_type=fedla --sec_agg --use_approx_updates --dropout=1 --first_dropout_epoch=1 --last_dropout_epoch=100 --local_dp --max_grad_norm=8.0 --iid_epsilon=1.0 --non_iid_epsilon=1.0 --delta=1e-5 && \
python federated_main.py --dataset=emnist-balanced --epochs=100 --local_ep=10 --lr=0.01 --frac=0.7 --unequal --num_samples_per_user=2400 --seed=42 --num_unique_classes_non_iid=1 --num_non_iid_users=7 --agg_type=fedla --sec_agg --use_approx_updates --dropout=1 --first_dropout_epoch=1 --last_dropout_epoch=100 --local_dp --max_grad_norm=8.0 --iid_epsilon=1.5 --non_iid_epsilon=1.5 --delta=1e-5

# local dp C = 9.0, epsilon = 0.4, 0.5, 0.6, 0.8, 1.0, 1.5, no SA
python federated_main.py --dataset=emnist-balanced --epochs=100 --local_ep=10 --lr=0.01 --frac=0.7 --unequal --num_samples_per_user=2400 --seed=42 --num_unique_classes_non_iid=1 --num_non_iid_users=7 --agg_type=fedla --sec_agg --use_approx_updates --dropout=1 --first_dropout_epoch=1 --last_dropout_epoch=100 --local_dp --max_grad_norm=9.0 --iid_epsilon=0.4 --non_iid_epsilon=0.4 --delta=1e-5 && \
python federated_main.py --dataset=emnist-balanced --epochs=100 --local_ep=10 --lr=0.01 --frac=0.7 --unequal --num_samples_per_user=2400 --seed=42 --num_unique_classes_non_iid=1 --num_non_iid_users=7 --agg_type=fedla --sec_agg --use_approx_updates --dropout=1 --first_dropout_epoch=1 --last_dropout_epoch=100 --local_dp --max_grad_norm=9.0 --iid_epsilon=0.5 --non_iid_epsilon=0.5 --delta=1e-5 && \
python federated_main.py --dataset=emnist-balanced --epochs=100 --local_ep=10 --lr=0.01 --frac=0.7 --unequal --num_samples_per_user=2400 --seed=42 --num_unique_classes_non_iid=1 --num_non_iid_users=7 --agg_type=fedla --sec_agg --use_approx_updates --dropout=1 --first_dropout_epoch=1 --last_dropout_epoch=100 --local_dp --max_grad_norm=9.0 --iid_epsilon=0.6 --non_iid_epsilon=0.6 --delta=1e-5 && \
python federated_main.py --dataset=emnist-balanced --epochs=100 --local_ep=10 --lr=0.01 --frac=0.7 --unequal --num_samples_per_user=2400 --seed=42 --num_unique_classes_non_iid=1 --num_non_iid_users=7 --agg_type=fedla --sec_agg --use_approx_updates --dropout=1 --first_dropout_epoch=1 --last_dropout_epoch=100 --local_dp --max_grad_norm=9.0 --iid_epsilon=0.8 --non_iid_epsilon=0.8 --delta=1e-5 && \
python federated_main.py --dataset=emnist-balanced --epochs=100 --local_ep=10 --lr=0.01 --frac=0.7 --unequal --num_samples_per_user=2400 --seed=42 --num_unique_classes_non_iid=1 --num_non_iid_users=7 --agg_type=fedla --sec_agg --use_approx_updates --dropout=1 --first_dropout_epoch=1 --last_dropout_epoch=100 --local_dp --max_grad_norm=9.0 --iid_epsilon=1.0 --non_iid_epsilon=1.0 --delta=1e-5 && \
python federated_main.py --dataset=emnist-balanced --epochs=100 --local_ep=10 --lr=0.01 --frac=0.7 --unequal --num_samples_per_user=2400 --seed=42 --num_unique_classes_non_iid=1 --num_non_iid_users=7 --agg_type=fedla --sec_agg --use_approx_updates --dropout=1 --first_dropout_epoch=1 --last_dropout_epoch=100 --local_dp --max_grad_norm=9.0 --iid_epsilon=1.5 --non_iid_epsilon=1.5 --delta=1e-5

# local dp C = 10.0, epsilon = 0.4, 0.5, 0.6, 0.8, 1.0, 1.5, no SA
python federated_main.py --dataset=emnist-balanced --epochs=100 --local_ep=10 --lr=0.01 --frac=0.7 --unequal --num_samples_per_user=2400 --seed=42 --num_unique_classes_non_iid=1 --num_non_iid_users=7 --agg_type=fedla --sec_agg --use_approx_updates --dropout=1 --first_dropout_epoch=1 --last_dropout_epoch=100 --local_dp --max_grad_norm=10.0 --iid_epsilon=0.4 --non_iid_epsilon=0.4 --delta=1e-5 && \
python federated_main.py --dataset=emnist-balanced --epochs=100 --local_ep=10 --lr=0.01 --frac=0.7 --unequal --num_samples_per_user=2400 --seed=42 --num_unique_classes_non_iid=1 --num_non_iid_users=7 --agg_type=fedla --sec_agg --use_approx_updates --dropout=1 --first_dropout_epoch=1 --last_dropout_epoch=100 --local_dp --max_grad_norm=10.0 --iid_epsilon=0.5 --non_iid_epsilon=0.5 --delta=1e-5 && \
python federated_main.py --dataset=emnist-balanced --epochs=100 --local_ep=10 --lr=0.01 --frac=0.7 --unequal --num_samples_per_user=2400 --seed=42 --num_unique_classes_non_iid=1 --num_non_iid_users=7 --agg_type=fedla --sec_agg --use_approx_updates --dropout=1 --first_dropout_epoch=1 --last_dropout_epoch=100 --local_dp --max_grad_norm=10.0 --iid_epsilon=0.6 --non_iid_epsilon=0.6 --delta=1e-5 && \
python federated_main.py --dataset=emnist-balanced --epochs=100 --local_ep=10 --lr=0.01 --frac=0.7 --unequal --num_samples_per_user=2400 --seed=42 --num_unique_classes_non_iid=1 --num_non_iid_users=7 --agg_type=fedla --sec_agg --use_approx_updates --dropout=1 --first_dropout_epoch=1 --last_dropout_epoch=100 --local_dp --max_grad_norm=10.0 --iid_epsilon=0.8 --non_iid_epsilon=0.8 --delta=1e-5 && \
python federated_main.py --dataset=emnist-balanced --epochs=100 --local_ep=10 --lr=0.01 --frac=0.7 --unequal --num_samples_per_user=2400 --seed=42 --num_unique_classes_non_iid=1 --num_non_iid_users=7 --agg_type=fedla --sec_agg --use_approx_updates --dropout=1 --first_dropout_epoch=1 --last_dropout_epoch=100 --local_dp --max_grad_norm=10.0 --iid_epsilon=1.0 --non_iid_epsilon=1.0 --delta=1e-5 && \
python federated_main.py --dataset=emnist-balanced --epochs=100 --local_ep=10 --lr=0.01 --frac=0.7 --unequal --num_samples_per_user=2400 --seed=42 --num_unique_classes_non_iid=1 --num_non_iid_users=7 --agg_type=fedla --sec_agg --use_approx_updates --dropout=1 --first_dropout_epoch=1 --last_dropout_epoch=100 --local_dp --max_grad_norm=10.0 --iid_epsilon=1.5 --non_iid_epsilon=1.5 --delta=1e-5

python federated_main.py --dataset=emnist-balanced --epochs=100 --local_ep=10 --lr=0.01 --frac=0.7 --unequal --num_samples_per_user=2400 --seed=42 --num_unique_classes_non_iid=1 --num_non_iid_users=7 --agg_type=fedla --sec_agg --use_approx_updates --dropout=1 --first_dropout_epoch=1 --last_dropout_epoch=100 --local_dp --max_grad_norm=7.0 --iid_epsilon=1.0 --non_iid_epsilon=0.5 --delta=1e-5 && \
python federated_main.py --dataset=emnist-balanced --epochs=100 --local_ep=10 --lr=0.01 --frac=0.7 --unequal --num_samples_per_user=2400 --seed=42 --num_unique_classes_non_iid=1 --num_non_iid_users=7 --agg_type=fedla --sec_agg --use_approx_updates --dropout=1 --first_dropout_epoch=1 --last_dropout_epoch=100 --local_dp --max_grad_norm=7.0 --iid_epsilon=2.0 --non_iid_epsilon=1.0 --delta=1e-5 && \
python federated_main.py --dataset=emnist-balanced --epochs=100 --local_ep=10 --lr=0.01 --frac=0.7 --unequal --num_samples_per_user=2400 --seed=42 --num_unique_classes_non_iid=1 --num_non_iid_users=7 --agg_type=fedla --sec_agg --use_approx_updates --dropout=1 --first_dropout_epoch=1 --last_dropout_epoch=100 --local_dp --max_grad_norm=7.0 --iid_epsilon=3.0 --non_iid_epsilon=1.5 --delta=1e-5 && \
python federated_main.py --dataset=emnist-balanced --epochs=100 --local_ep=10 --lr=0.01 --frac=0.7 --unequal --num_samples_per_user=2400 --seed=42 --num_unique_classes_non_iid=1 --num_non_iid_users=7 --agg_type=fedla --sec_agg --use_approx_updates --dropout=1 --first_dropout_epoch=1 --last_dropout_epoch=100 --local_dp --max_grad_norm=7.0 --iid_epsilon=4.0 --non_iid_epsilon=2.0 --delta=1e-5 && \
python federated_main.py --dataset=emnist-balanced --epochs=100 --local_ep=10 --lr=0.01 --frac=0.7 --unequal --num_samples_per_user=2400 --seed=42 --num_unique_classes_non_iid=1 --num_non_iid_users=7 --agg_type=fedla --sec_agg --use_approx_updates --dropout=1 --first_dropout_epoch=1 --last_dropout_epoch=100 --local_dp --max_grad_norm=7.0 --iid_epsilon=5.0 --non_iid_epsilon=2.5 --delta=1e-5
python federated_main.py --dataset=emnist-balanced --epochs=100 --local_ep=10 --lr=0.01 --frac=0.7 --unequal --num_samples_per_user=2400 --seed=42 --num_unique_classes_non_iid=1 --num_non_iid_users=7 --agg_type=fedla --sec_agg --use_approx_updates --dropout=1 --first_dropout_epoch=1 --last_dropout_epoch=100 --local_dp --max_grad_norm=7.0 --iid_epsilon=10.0 --non_iid_epsilon=5.0 --delta=1e-5

python federated_main.py --dataset=emnist-balanced --epochs=100 --local_ep=10 --lr=0.01 --frac=0.7 --unequal --num_samples_per_user=2400 --seed=42 --num_unique_classes_non_iid=1 --num_non_iid_users=7 --agg_type=fedla --sec_agg --use_approx_updates --dropout=1 --first_dropout_epoch=1 --last_dropout_epoch=100 --local_dp --max_grad_norm=7.0 --iid_epsilon=2.0 --non_iid_epsilon=2.0 --delta=1e-5 && \
python federated_main.py --dataset=emnist-balanced --epochs=100 --local_ep=10 --lr=0.01 --frac=0.7 --unequal --num_samples_per_user=2400 --seed=42 --num_unique_classes_non_iid=1 --num_non_iid_users=7 --agg_type=fedla --sec_agg --use_approx_updates --dropout=1 --first_dropout_epoch=1 --last_dropout_epoch=100 --local_dp --max_grad_norm=7.0 --iid_epsilon=1.0 --non_iid_epsilon=2.0 --delta=1e-5 && \
python federated_main.py --dataset=emnist-balanced --epochs=100 --local_ep=10 --lr=0.01 --frac=0.7 --unequal --num_samples_per_user=2400 --seed=42 --num_unique_classes_non_iid=1 --num_non_iid_users=7 --agg_type=fedla --sec_agg --use_approx_updates --dropout=1 --first_dropout_epoch=1 --last_dropout_epoch=100 --local_dp --max_grad_norm=7.0 --iid_epsilon=1.5 --non_iid_epsilon=3.0 --delta=1e-5 && \
python federated_main.py --dataset=emnist-balanced --epochs=100 --local_ep=10 --lr=0.01 --frac=0.7 --unequal --num_samples_per_user=2400 --seed=42 --num_unique_classes_non_iid=1 --num_non_iid_users=7 --agg_type=fedla --sec_agg --use_approx_updates --dropout=1 --first_dropout_epoch=1 --last_dropout_epoch=100 --local_dp --max_grad_norm=7.0 --iid_epsilon=4.0 --non_iid_epsilon=2.0 --delta=1e-5 && \
python federated_main.py --dataset=emnist-balanced --epochs=100 --local_ep=10 --lr=0.01 --frac=0.7 --unequal --num_samples_per_user=2400 --seed=42 --num_unique_classes_non_iid=1 --num_non_iid_users=7 --agg_type=fedla --sec_agg --use_approx_updates --dropout=1 --first_dropout_epoch=1 --last_dropout_epoch=100 --local_dp --max_grad_norm=7.0 --iid_epsilon=5.0 --non_iid_epsilon=2.5 --delta=1e-5
python federated_main.py --dataset=emnist-balanced --epochs=100 --local_ep=10 --lr=0.01 --frac=0.7 --unequal --num_samples_per_user=2400 --seed=42 --num_unique_classes_non_iid=1 --num_non_iid_users=7 --agg_type=fedla --sec_agg --use_approx_updates --dropout=1 --first_dropout_epoch=1 --last_dropout_epoch=100 --local_dp --max_grad_norm=7.0 --iid_epsilon=10.0 --non_iid_epsilon=5.0 --delta=1e-5

python federated_main.py --dataset=emnist-balanced --epochs=100 --local_ep=10 --lr=0.01 --frac=0.7 --unequal --num_samples_per_user=2400 --seed=42 --num_unique_classes_non_iid=1 --num_non_iid_users=7 --agg_type=fedla --sec_agg --use_approx_updates --dropout=1 --first_dropout_epoch=1 --last_dropout_epoch=100 --local_dp --max_grad_norm=7.0 --iid_epsilon=2.0 --non_iid_epsilon=2.0 --delta=1e-5
python federated_main.py --dataset=emnist-balanced --epochs=100 --local_ep=10 --lr=0.01 --frac=0.8 --unequal --num_samples_per_user=2400 --seed=42 --num_unique_classes_non_iid=1 --num_non_iid_users=7 --agg_type=fedla --sec_agg --use_approx_updates --dropout=2 --first_dropout_epoch=1 --last_dropout_epoch=100 --local_dp --max_grad_norm=7.0 --iid_epsilon=2.0 --non_iid_epsilon=2.0 --delta=1e-5
python federated_main.py --dataset=emnist-balanced --epochs=100 --local_ep=10 --lr=0.01 --frac=0.9 --unequal --num_samples_per_user=2400 --seed=42 --num_unique_classes_non_iid=1 --num_non_iid_users=7 --agg_type=fedla --sec_agg --use_approx_updates --dropout=3 --first_dropout_epoch=1 --last_dropout_epoch=100 --local_dp --max_grad_norm=7.0 --iid_epsilon=2.0 --non_iid_epsilon=2.0 --delta=1e-5

python federated_main.py --dataset=emnist-balanced --epochs=100 --local_ep=10 --lr=0.01 --frac=0.7 --unequal --num_samples_per_user=2400 --seed=42 --num_unique_classes_non_iid=1 --num_non_iid_users=7 --agg_type=fedla --sec_agg --dropout=1 --first_dropout_epoch=1 --last_dropout_epoch=100
python federated_main.py --dataset=emnist-balanced --epochs=100 --local_ep=10 --lr=0.01 --frac=0.8 --unequal --num_samples_per_user=2400 --seed=42 --num_unique_classes_non_iid=1 --num_non_iid_users=7 --agg_type=fedla --sec_agg --dropout=2 --first_dropout_epoch=1 --last_dropout_epoch=100
python federated_main.py --dataset=emnist-balanced --epochs=100 --local_ep=10 --lr=0.01 --frac=0.9 --unequal --num_samples_per_user=2400 --seed=42 --num_unique_classes_non_iid=1 --num_non_iid_users=7 --agg_type=fedla --sec_agg --dropout=3 --first_dropout_epoch=1 --last_dropout_epoch=100

python federated_main.py --dataset=emnist-balanced --epochs=100 --local_ep=10 --lr=0.01 --frac=0.7 --unequal --num_samples_per_user=2400 --seed=42 --num_unique_classes_non_iid=1 --num_non_iid_users=7 --agg_type=fedla --sec_agg --use_approx_updates --dropout=1 --first_dropout_epoch=1 --last_dropout_epoch=100 --local_dp --max_grad_norm=7.0 --iid_epsilon=2.0 --non_iid_epsilon=2.0 --delta=1e-5
python federated_main.py --dataset=emnist-balanced --epochs=100 --local_ep=10 --lr=0.01 --frac=0.8 --unequal --num_samples_per_user=2400 --seed=42 --num_unique_classes_non_iid=1 --num_non_iid_users=7 --agg_type=fedla --sec_agg --use_approx_updates --dropout=2 --first_dropout_epoch=1 --last_dropout_epoch=100 --local_dp --max_grad_norm=7.0 --iid_epsilon=2.0 --non_iid_epsilon=2.0 --delta=1e-5
python federated_main.py --dataset=emnist-balanced --epochs=100 --local_ep=10 --lr=0.01 --frac=0.9 --unequal --num_samples_per_user=2400 --seed=42 --num_unique_classes_non_iid=1 --num_non_iid_users=7 --agg_type=fedla --sec_agg --use_approx_updates --dropout=3 --first_dropout_epoch=1 --last_dropout_epoch=100 --local_dp --max_grad_norm=7.0 --iid_epsilon=2.0 --non_iid_epsilon=2.0 --delta=1e-5

python federated_main.py --dataset=emnist-balanced --epochs=100 --local_ep=10 --lr=0.01 --frac=0.7 --unequal --num_samples_per_user=2400 --seed=42 --num_unique_classes_non_iid=1 --num_non_iid_users=7 --agg_type=fedavg --fedavg_type=unweighted --local_dp --max_grad_norm=7.0 --iid_epsilon=2.0 --non_iid_epsilon=2.0 --delta=1e-5
python federated_main.py --dataset=emnist-balanced --epochs=100 --local_ep=10 --lr=0.01 --frac=0.8 --unequal --num_samples_per_user=2400 --seed=42 --num_unique_classes_non_iid=1 --num_non_iid_users=7 --agg_type=fedavg --fedavg_type=unweighted --local_dp --max_grad_norm=7.0 --iid_epsilon=2.0 --non_iid_epsilon=2.0 --delta=1e-5
python federated_main.py --dataset=emnist-balanced --epochs=100 --local_ep=10 --lr=0.01 --frac=0.9 --unequal --num_samples_per_user=2400 --seed=42 --num_unique_classes_non_iid=1 --num_non_iid_users=7 --agg_type=fedavg --fedavg_type=unweighted --local_dp --max_grad_norm=7.0 --iid_epsilon=2.0 --non_iid_epsilon=2.0 --delta=1e-5

python federated_main.py --dataset=emnist-balanced --epochs=100 --local_ep=10 --lr=0.01 --frac=0.7 --unequal --num_samples_per_user=2400 --seed=42 --iid --agg_type=fedavg --fedavg_type=unweighted --local_dp --max_grad_norm=7.0 --iid_epsilon=2.0 --non_iid_epsilon=2.0 --delta=1e-5
python federated_main.py --dataset=emnist-balanced --epochs=100 --local_ep=10 --lr=0.01 --frac=0.8 --unequal --num_samples_per_user=2400 --seed=42 --iid --agg_type=fedavg --fedavg_type=unweighted --local_dp --max_grad_norm=7.0 --iid_epsilon=2.0 --non_iid_epsilon=2.0 --delta=1e-5
python federated_main.py --dataset=emnist-balanced --epochs=100 --local_ep=10 --lr=0.01 --frac=0.9 --unequal --num_samples_per_user=2400 --seed=42 --iid --agg_type=fedavg --fedavg_type=unweighted --local_dp --max_grad_norm=7.0 --iid_epsilon=2.0 --non_iid_epsilon=2.0 --delta=1e-5

python federated_main.py --dataset=emnist-balanced --epochs=100 --local_ep=1 --lr=0.01 --frac=0.8 --unequal --num_samples_per_user=2400 --seed=42 --num_unique_classes_non_iid=1 --num_non_iid_users=7 --agg_type=fedla --sec_agg --use_approx_updates

python federated_main.py --dataset=emnist-balanced --epochs=100 --local_ep=10 --lr=0.01 --num_users=100 --frac=0.8 --unequal --num_samples_per_user=1000 --seed=42 --num_unique_classes_non_iid=1 --num_non_iid_users=7 --agg_type=fedla --sec_agg --dropout=20 --first_dropout_epoch=1 --last_dropout_epoch=100 --use_approx_updates